### ISSUE TITLE
Unable to read the configuration file netshot.conf.

### ISSUE THREAD

**Issue by achastre** [netfishers-onl/Netshot#10]
Hello,

I don't understand why i get this error.
netshot.conf is in the right path, i also try chmod 777 on it...

could you please advise me.

I work on a debian 9.

thanks for your support.
Arnaud

**Comment by sajaltiwari** [comment]
Can you paste the output of your folder structure?

**Comment by SCadilhac** [comment]
Hi @achastre
At startup, Netshot first tries to read netshot.conf in the local path and prints a message if it can't. The error message your are mentioning may be safely ignored, as Netshot will then try to read /etc/netshot.conf, which should succeed in your case.

**Comment by achastre** [comment]
Hi @SCadilhac ,
thanks for the feedback.
As i saw this error i didn't read further the syslog... the process is still not starting.
here is the result in the log file.


May 16 09:32:40 debian-vb-arnaud systemd[1]: Started Netshot.
May 16 09:32:41 debian-vb-arnaud java[1162]: Starting Netshot version 0.7.1.
May 16 09:32:41 debian-vb-arnaud java[1162]: 09:32:41.141 [main] INFO onl.netfishers.netshot.Netshot - Starting Netshot
May 16 09:32:41 debian-vb-arnaud java[1162]: 09:32:41.146 [main] ERROR onl.netfishers.netshot.Netshot - Unable to read the configuration file netshot.conf.
May 16 09:32:41 debian-vb-arnaud java[1162]: 09:32:41.157 [main] INFO onl.netfishers.netshot.Netshot - Switching to file logging, into /var/log/netshot/netshot.log, level WARN, rotation using 5 files of max 2MB.
May 16 09:32:41 debian-vb-arnaud java[1162]: Exception in thread "main" java.lang.NoClassDefFoundError: org/hibernate/HibernateException
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at onl.netfishers.netshot.Netshot.main(Netshot.java:313)
May 16 09:32:41 debian-vb-arnaud java[1162]: Caused by: java.lang.ClassNotFoundException: org.hibernate.HibernateException
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.security.AccessController.doPrivileged(Native Method)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011... 1 more
May 16 09:32:41 debian-vb-arnaud java[1162]: Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.util.zip.ZipFile.read(Native Method)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at sun.misc.Resource.getBytes(Resource.java:124)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
May 16 09:32:41 debian-vb-arnaud java[1162]: #011... 7 more
May 16 09:32:41 debian-vb-arnaud systemd[1]: netshot.service: Main process exited, code=exited, status=1/FAILURE
May 16 09:32:41 debian-vb-arnaud systemd[1]: netshot.service: Unit entered failed state.
May 16 09:32:41 debian-vb-arnaud systemd[1]: netshot.service: Failed with result 'exit-code'.

**Comment by SCadilhac** [comment]
HI @achastre 

This looks like a corrupted file. You might want to re-download and re-install `netshot.jar`.

**Comment by achastre** [comment]
Hi @SCadilhac 

Thanks a lot :) it works now.
