### ISSUE TITLE
Netshot Frontend connection problems.

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#101]
Hi,

I'm having a weird issue, we wanted to add some reports option and we manage to do it.
before adding it we tested it on a empty Netshot image that we had with no devices and everything worked .

so we decided to add it to the production server. ( following the procedure of backing up everything )
This VM of Netshot is currently managing over 1500 devices.

Once the netshot.jar copied, we then restarted the Netshot service and nothing , we can see in the background everything seams to be working , but i cannot see the main page, I'm getting ether an Connection Refused or err timeout.

So we did revert the VM to a previous state working , and same problem. This VM didn't had any restart for a long time.

I'm under the impression that everything is working in the background but i don't have access tp the frontend.

On Firefox Im getting this error : An error occurred during a connection to XX.XX.XX.XX:8443. PR_END_OF_FILE_ERROR

I have attached the following logs :

*****************************************

Again Thank you for this amazing application.

Patrick D

**Comment by PatrickDenis** [comment]
I was able to dump the DB and restore it on a new VM, everything works now. 

Is it possible that because we didn't restart the server for a very long time this could happen ?

From that experience, it would be nice in the next update  "17" to have an automatic DB backup option :)


As always , Thank you for that great piece of work :)

**Comment by SCadilhac** [comment]
Hi @PatrickDenis, I get everything is working now... What version did you upgrade from and to?

**Comment by PatrickDenis** [comment]
Hi @SCadilhac, did use the same Version , i have pre made an OVA as a backup and use the dump DB in it and everything working now.

i have tried to use the latest version , but i havent been successful "yet" for converting the DB from mysql to postg.
will try again next week. 

Lesson learn tho, i will always use a new instance from now own and restore the DB.

Again thank you for this amazing product !

**Comment by PatrickDenis** [comment]
Lesson Learn :)

**Comment by PatrickDenis** [comment]
So after having the same issue on a new instance i decided to make a new one again to tshoot it since after a while ,that new instance came back.

I then restart the VM and it did happen again i cannot access the frontend anymore.

i found through the /var/log/syslog that when this message pop  up ! it then start working again 

Mar 11 16:39:21 ccms systemd-resolved[770]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.

the minute that message appears , the frontend works ?
