### ISSUE TITLE
Configuration changes. Field 'Author' is empty

### ISSUE THREAD

**Issue by myroma** [netfishers-onl/Netshot#103]
Field 'Author' at Configuration changes tab is empty.
I am seeing the issue in versions 0.16.0 and 0.16.1

**Comment by SCadilhac** [comment]
That field is not filled in by all drivers. For some devices, you can guess who indeed performed the change.

**Comment by myroma** [comment]
I used to view that field on Cisco devices.

**Comment by SCadilhac** [comment]
Fixed in 3fe3b91024e95addf1f3ac8c61220a2e175ec14c
