### ISSUE TITLE
autosnapshot

### ISSUE THREAD

**Issue by myroma** [netfishers-onl/Netshot#105]
Auto Snapshot is not happening after Syslog messages receive.

**Comment by SCadilhac** [comment]
* This not supported by all device drivers.
* The default port Netshot listens to is 1514 (to avoid running as root), you may need a port translation (as explained in the installation guide) to redirect 514 to 1514.
* Any message in the logs?

**Comment by myroma** [comment]
1) I am talking about Cisco devices
2) I know that
3) i have got messages in the log

**Comment by SCadilhac** [comment]
Should be fixed by 08f882973a08556813c4f3d2bdfee2561bce652e
Thanks for reporting.
