### ISSUE TITLE
MySQL to PostgreSQL migration

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#106]
So quick story short,   did a brand new install of the Netshot V16 , everything works started netshot and it worked 1st try.

Then i did a service netshot stop on both instance.

then created the file migrate.load as is : 

LOAD DATABASE
    FROM mysql://old_server_user:old_server_pass@{IP_OLD_SERVER}/netshot01               <---- OLD SERVER
    INTO postgresql://old_server_user:old_server_pass@localhost/netshot01                      <---  NEW SERVER
WITH include no drop, create no tables, create no indexes, reset sequences,
    batch rows = 10, prefetch rows = 10
ALTER SCHEMA 'netshot01' RENAME TO 'public';

then i installed pgloader to execute the migrate.load

Then I'm getting this errors : 

**ccms@ccms:~$ pgloader migrate.load**

2021-03-11T01:41:41.021000Z LOG pgloader version "3.6.1"
KABOOM!
FATAL error: Failed to connect to pgsql at "localhost" (port 5432) as user "ccms": Database error 28P01: password authentication failed for user "ccms"
An unhandled error condition has been signalled:
   Failed to connect to pgsql at "localhost" (port 5432) as user "ccms": Database error 28P01: password authentication failed for user "ccms"

What I am doing here?

Failed to connect to pgsql at "localhost" (port 5432) as user "ccms": Database error 28P01: password authentication failed for user "ccms"

**ccms@ccms:~$ cat /var/log/postgresql/postgresql-12-main.log** 

2021-03-11 01:16:26.060 UTC [9188] netshot@netshot01 FATAL:  password authentication failed for user "netshot"
2021-03-11 01:16:26.060 UTC [9188] netshot@netshot01 DETAIL:  Password does not match for user "netshot".
        Connection matched pg_hba.conf line 96: "host    all             all             127.0.0.1/32            md5"
2021-03-11 01:41:41.736 UTC [9938] ccms@netshot01 FATAL:  password authentication failed for user "ccms"
2021-03-11 01:41:41.736 UTC [9938] ccms@netshot01 DETAIL:  Role "ccms" does not exist.
        Connection matched pg_hba.conf line 96: "host    all             all             127.0.0.1/32            md5"

So my guess is that i didn't understand those 2 lines configurations from migrate.load  : 

    FROM mysql://old_server_user:old_server_pass@{IP_OLD_SERVER}/netshot01               <---- OLD SERVER
    INTO postgresql://old_server_user:old_server_pass@localhost/netshot01                      <---  NEW SERVER

So for FROM mysql://{{input1}}:{{}input2}@{IP_OLD_SERVER}/netshot01
is input1 the username of the actual server or the sql database ?
is input2 the password of the server or the database ?

I'm confused :)

but almost there !

Thank you again for everything !

**Comment by SCadilhac** [comment]
All usernames/passwords here are DB credentials.
`pgloader` is assumed to be executed from the *new* server.
You need to ensure the given MySQL user is allowed to connect remotely to the former server's MySQL.

**Comment by PatrickDenis** [comment]
Ok following this article i was able to connect : https://linuxize.com/post/mysql-remote-access/

but now I'm getting this error :  

root@CCMSV16:/home/ccms# pgloader migrate.load
2021-03-11T12:37:29.027000Z LOG pgloader version "3.6.1"
2021-03-11T12:37:29.034000Z LOG Parsing commands from file #P"/home/ccms/migrate.load"
2021-03-11T12:37:29.198000Z LOG Migrating from #<MYSQL-CONNECTION mysql://netshot@xx.xx.xx.xx3306/netshot01 {100694D593}>
2021-03-11T12:37:29.199000Z LOG Migrating into #<PGSQL-CONNECTION pgsql://netshot@localhost:5432/netshot01 {100694EAD3}>
2021-03-11T12:37:30.106000Z ERROR Database error 42703: column "adsrc" does not exist
QUERY: -- params: table-type-name
--         including
--         filter-list-to-where-clause for including
--         excluding
--         filter-list-to-where-clause for excluding
with seqattr as
 (
   select adrelid, 
          adnum,
          adsrc,
          case when adsrc ~ 'nextval'
               then substring(pg_get_expr(d.adbin, d.adrelid)
                              from '''([^'']+)'''
                    )
               else null
           end as seqname
     from pg_attrdef d
 )
    select nspname, relname, c.oid, attname,
           t.oid::regtype as type,
           case when atttypmod > 0
                then substring(format_type(t.oid, atttypmod) from '\d+(?:,\d+)?')
                else null
            end as typmod,
           attnotnull,
           case when atthasdef then def.adsrc end as default,
           case when s.seqname is not null then 'auto_increment' end as extra
      from pg_class c
           join pg_namespace n on n.oid = c.relnamespace
           left join pg_attribute a on c.oid = a.attrelid
           join pg_type t on t.oid = a.atttypid and attnum > 0
           left join pg_attrdef def on a.attrelid = def.adrelid
                                   and a.attnum = def.adnum
                                   and a.atthasdef
           left join seqattr s on def.adrelid = s.adrelid
                              and def.adnum = s.adnum

     where nspname !~ '^pg_' and n.nspname <> 'information_schema'
           and relkind in ('r', 'f', 'p')
           and ((n.nspname = 'public' and c.relname = 'check_compliance_task')
           or (n.nspname = 'public' and c.relname = 'check_group_compliance_task')
           or (n.nspname = 'public' and c.relname = 'check_group_software_task')
           or (n.nspname = 'public' and c.relname = 'check_result')
           or (n.nspname = 'public' and c.relname = 'config')
           or (n.nspname = 'public' and c.relname = 'config_attribute')
           or (n.nspname = 'public' and c.relname = 'databasechangelog')
           or (n.nspname = 'public' and c.relname = 'databasechangeloglock')
           or (n.nspname = 'public' and c.relname = 'debug_log')
           or (n.nspname = 'public' and c.relname = 'device')
           or (n.nspname = 'public' and c.relname = 'device_attribute')
           or (n.nspname = 'public' and c.relname = 'device_credential_set')
           or (n.nspname = 'public' and c.relname = 'device_credential_sets')
           or (n.nspname = 'public' and c.relname = 'device_group')
           or (n.nspname = 'public' and c.relname = 'device_group_cached_devices')
           or (n.nspname = 'public' and c.relname = 'device_js_script')
           or (n.nspname = 'public' and c.relname = 'device_virtual_devices')
           or (n.nspname = 'public' and c.relname = 'device_vrf_instances')
           or (n.nspname = 'public' and c.relname = 'diagnostic')
           or (n.nspname = 'public' and c.relname = 'diagnostic_result')
           or (n.nspname = 'public' and c.relname = 'discover_device_type_task')
           or (n.nspname = 'public' and c.relname = 'discover_device_type_task_credential_sets')
           or (n.nspname = 'public' and c.relname = 'domain')
           or (n.nspname = 'public' and c.relname = 'dynamic_device_group')
           or (n.nspname = 'public' and c.relname = 'exemption')
           or (n.nspname = 'public' and c.relname = 'hardware_rule')
           or (n.nspname = 'public' and c.relname = 'java_script_diagnostic')
           or (n.nspname = 'public' and c.relname = 'java_script_rule')
           or (n.nspname = 'public' and c.relname = 'long_text_configuration')
           or (n.nspname = 'public' and c.relname = 'module')
           or (n.nspname = 'public' and c.relname = 'network_interface')
           or (n.nspname = 'public' and c.relname = 'network_interface_ip4addresses')
           or (n.nspname = 'public' and c.relname = 'network_interface_ip6addresses')
           or (n.nspname = 'public' and c.relname = 'policy')
           or (n.nspname = 'public' and c.relname = 'purge_database_task')
           or (n.nspname = 'public' and c.relname = 'rule')
           or (n.nspname = 'public' and c.relname = 'run_device_group_script_task')
           or (n.nspname = 'public' and c.relname = 'run_device_script_task')
           or (n.nspname = 'public' and c.relname = 'run_diagnostics_task')
           or (n.nspname = 'public' and c.relname = 'run_group_diagnostics_task')
           or (n.nspname = 'public' and c.relname = 'scan_subnets_task')
           or (n.nspname = 'public' and c.relname = 'scan_subnets_task_subnets')
           or (n.nspname = 'public' and c.relname = 'simple_diagnostic')
           or (n.nspname = 'public' and c.relname = 'software_rule')
           or (n.nspname = 'public' and c.relname = 'static_device_group')
           or (n.nspname = 'public' and c.relname = 'take_group_snapshot_task')
           or (n.nspname = 'public' and c.relname = 'take_snapshot_task')
           or (n.nspname = 'public' and c.relname = 'task')
           or (n.nspname = 'public' and c.relname = 'text_rule')
           or (n.nspname = 'public' and c.relname = 'user'))
           

  order by nspname, relname, attnum;
2021-03-11T12:37:30.107000Z FATAL Failed to create the schema, see above.
2021-03-11T12:37:30.113000Z LOG report summary reset
       table name     errors       rows      bytes      total time
-----------------  ---------  ---------  ---------  --------------
  fetch meta data          0        116                     0.233s
-----------------  ---------  ---------  ---------  --------------
-----------------  ---------  ---------  ---------  --------------
root@CCMSV16:/home/ccms# 

Almost there !!!!

**Comment by SCadilhac** [comment]
You might want either to use PostgreSQL 11.x or to upgrade pgloader.

**Comment by PatrickDenis** [comment]
Im using : 
pgloader version "3.6.1"
compiled with SBCL 1.4.15.debian

and psql (PostgreSQL) 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)

**Comment by PatrickDenis** [comment]
By Upgrading to pgloader 3.6.2 the migration did work.

**Comment by PatrickDenis** [comment]
just wanted to add some info so if anyone have some issue these helped for me on Ubuntu20.04:

1- Enable binding on the .cnf for mysql  by adding the ip of the remote server
2- Make sure the user are allows to connect remotely to the sql server
3- Execute pgloader with the script Netshot Provided "migrate.load"

Thank you again Sylvain for this amazing application
