### ISSUE TITLE
Reports Netshot V16 ( Can any one confirm  ? )

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#108]
In Version 16, Can anyone confirm that in Reports , the Graphs are showing up ?

Also the export to excel is giving me an HTTP ERROR 500

Here's the logs.

[Reports.logs.txt](https://github.com/netfishers-onl/Netshot/files/6198658/Reports.logs.txt)

Thank  you :)

**Comment by kedare** [comment]
If by reports you mean charts (like the pie charts), they are working fine for me (I compile directly on master).

**Comment by SCadilhac** [comment]
This seems to relate to the number of groups in the instance. Need to improve this view to support more groups in a way or another.
