### ISSUE TITLE
Module policy ?

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#109]
Hello.

I have been trying to create a policy that would check the hardware modules from the devices, but I could not find a way, it looks like this is not currently possible ?
In my example I am trying to create a policy that would check that all the fans are working in the same direction (so all FAN PART-ID are intake from front or intake from back)

Thanks

**Comment by SCadilhac** [comment]
From a Javascript rule, you can access the module list using `const modules = device.get("modules");`. A simple loop over it should do the job.
Note: I just patched a bug on this, so please use the last code, or a pre-0.16.x version for this to work.

**Comment by kedare** [comment]
Thank, I did not play the Javascript or Python policies yet, I will take a look.
Do you know if there are others examples available somewhere ? I only found the IS-IS one
