### ISSUE TITLE
Inconsistency between JS and Python scripts

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#110]
Hello.

I have been trying to create a policy in Python using the `modules` but looks like I am not getting the same thing than on JS, I cannot iterate of over the result nor access anything on it, for example this work in JS:

``` javascript
function check(device) {
    var modules = device.get("modules")
    print(modules[0].partNumber)
    return CONFORMING;
}

> N9K-C9364C
```

But this doesn't work in Python

``` python
def check(device):
  modules = device.get("modules")
  print(modules[0].partNumber)
  return result_option.CONFORMING

> 2021-03-30 15:36:31,647 ERROR [grizzly-http-server-14] PythonRule: Error while running the script on device 1.
org.graalvm.polyglot.PolyglotException: AttributeError: JavaObject[[Ljava.lang.Object;@53c93d1b (java.lang.Object[])] instance has no attribute '__getitem__'

```

Am I missing something on how to use the Python rules ? Looks like it's not correctly mapping java lists to python `list` class

Thanks

**Comment by SCadilhac** [comment]
Indeed, thanks for reporting, should be fixed by 064bdf8534aa97615b841f5058aee33c451fb9a7

**Comment by SCadilhac** [comment]
Not actually - the code architecture is not great in this aspect, at the moment but "camelization" is achieved by the Python interface.

**Comment by SCadilhac** [comment]
Yes indeed

**Comment by kedare** [comment]
Great, I will try that, thank you :)
