### ISSUE TITLE
Some blocks are missing in FortiOS 6.2

### ISSUE THREAD

**Issue by Najihel** [netfishers-onl/Netshot#115]
Hi,

Since the FortiOS 6.2, some blocks are missing in the `show` command executed from the root CLI (Fortinet BugID 0691228).

Could you update the FortiOS driver to execute theses commands from `config global` and from each vdom :

```
show log fortianalyzer setting
show log fortianalyzer2 setting
show log fortianalyzer3 setting
show log fortianalyzer-cloud setting
show log syslogd setting
show log syslogd2 setting
show log syslogd3 setting
show log syslogd4 setting
```

Or maybe it's possible to execute a `show` from global and each vdom in instead of the `show` from the root.

Thanks

**Comment by SCadilhac** [comment]
Implemented f571679c1190f0404f39b71445b68dc84939b315
(driver version 4.2)
Thanks for reporting
