### ISSUE TITLE
PyDeviceHelper.get() should not translate the item parameter to camelCase

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#117]
Hello.

After trying to define custom rules on diagnostics commands, I saw the automatic translation from under_score to camelCase also happens on the `item` paraemter of `PyDeviceHelper.get()`,

So for example if you have diagnostics named like `NX-OS ELPD` or `nxos_elpd`, you would have no way to query them as `device.get("NX-OS ELPD")` would in reality query `NXOSELPD` and `device.get("nxos_elpd")` would query `nxosElpd`

I don't think this is an expected behaviour ? It makes sense to have this automated translaction on object methods, but it's very confusing if this is also expected to work like that on string parameters like this one 😅 

Thanks

**Comment by kedare** [comment]
I see two possible easy fix 

https://github.com/netfishers-onl/Netshot/blob/master/src/main/resources/interfaces/rule-loader.py#L43

Either we try first with camelized keys and if the result is none we try the original key, or we can add another method like `get_direct` or `get_raw`

**Comment by SCadilhac** [comment]
17479eb836c2cbace564135872ef783c83615686
Would that work for you?

**Comment by kedare** [comment]
Looks like it is working,

Thank you :)
