### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#120]
Hello,

Is there anything preventing from having multiple instances of NetShot pointing to the same DB ?
The idea is to spread the load (mostly for the jobs) and provide H.A but I don't know if there is any kind of coordination to make sure jobs are balanced and not ran twice, etc... ? How would the `netshot.snapshots.dump` work on this case ? 

Thanks

**Comment by SCadilhac** [comment]
There are quite a few changes required to transform Netshot in a multi-worker HA system. I'm currently working on it actually, that's the next big task.

**Comment by kedare** [comment]
Awesome :)

**Comment by SCadilhac** [comment]
https://github.com/netfishers-onl/Netshot/wiki/Clustering-and-High-Availability
