### ISSUE TITLE
Upgrade confirmation. From 0.15.2

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#123]
Hi,

Am going to upgrade but need to confirm something before.

If I go directly to 0.16.2 would be a problem? or it would be better to do it sequential?

0.15.2 > 0.16.0 > 0.16.1 > 0.16.2

Thanks.

**Comment by PatrickDenis** [comment]
I would start a new instance ( VM ) and then migrate the DB from the old one to the new ones. In case any issue could occur.
This way your playing safe.

Have a great day !

**Comment by SCadilhac** [comment]
As advised by @PatrickDenis be sure to have a backup of the DB before any action.
Apart from that, you can upgrade directly from 0.15.2 to 0.16.2, but as stated in the upgrade notes, you need to install the GraalVM JRE when switching to 0.16.x.

**Comment by pizu** [comment]
Thanks all for your answers, am going to perform the upgrade by the end of this month. - closing ticket.
