### ISSUE TITLE
Netshot.service start failed

### ISSUE THREAD

**Issue by wanghy124** [netfishers-onl/Netshot#125]
Hi,

I have installed Netshot 0.16.2 on RHEL 7 according to the Installation guides, but i cannot access the web. 
I install Netshot on my production enviroment but still failed, this time netshot.service cannot start, below is log.

Finally i edit the file netshot.service User=root instead of  User=netshot and it work. I can access netshot web now. 
But i am not sure if this change will cause any mistake since netshot run as root now.

[root@... netshot]# systemctl status netshot
● netshot.service - Netshot
   Loaded: loaded (/etc/systemd/system/netshot.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2021-04-29 00:49:07 CST; 4min 8s ago
  Process: 10115 ExecStart=/usr/bin/java -jar /usr/local/netshot/netshot.jar (code=exited, status=203/EXEC)
 Main PID: 10115 (code=exited, status=203/EXEC)

Apr 29 00:49:07 cnshncma002 systemd[1]: Started Netshot.
Apr 29 00:49:07 cnshncma002 systemd[1]: netshot.service: main process exited, code=exited, status=203/EXEC
Apr 29 00:49:07 cnshncma002 systemd[1]: Unit netshot.service entered failed state.
Apr 29 00:49:07 cnshncma002 systemd[1]: netshot.service failed.

**Comment by SCadilhac** [comment]
You should not run Netshot as root. I added some more instructions for RHEL in the installation guide.

**Comment by wanghy124** [comment]
Thanks for your update. My psql configuration is correct, but Netshot process could not start unless change 'User=root' in /etc/systemd/system/netshot.service.

**Comment by SCadilhac** [comment]
This seems to be specific to your installation/system. Can't help without more details.

**Comment by wanghy124** [comment]
Thanks

**Comment by wanghy124** [comment]
Hi SCadilhac,

I found out this is a permission problem about installation of GraalVM. 
```tar xvzf graalvm-ce-java11-linux-amd64-21.1.0.tar.gz``` <- this create files by default non-root user 
```drwxr-x--- 10 xxx xxx 319 May 27 16:19 graalvm-ce-java11-21.1.0``` <- netshot has no permission

```sudo mkdir /usr/lib/jvm``` <- this create jvm foler by root
```drwxr-x---   3 root root      53 May 27 13:58 jvm``` <- netshot has no permission

Below is my workaround.
```sudo -i```
```cd /usr/lib```
```chmod 777 jvm```
```cd /usr/lib/jvm```
```chown -R netshot graalvm-ce-java11-21.1.0```

The user netshot can run /usr/bin/java now.
```drwxrwxrwx   3 root root      53 May 27 13:58 jvm```
```drwxr-x--- 10 netshot xxx 319 May 27 16:19 graalvm-ce-java11-21.1.0```

**Comment by SCadilhac** [comment]
Thanks for the feedback. I've adjusted the instructions. But you shouldn't give 777 permissions fo the Graal directory.
