### ISSUE TITLE
Add Fortigate cannot retrieve name, version and interface info

### ISSUE THREAD

**Issue by wanghy124** [netfishers-onl/Netshot#126]
I add a fortigate to netshot and take snapshot successfully, but it show 'Name [NONAME]' and 'Software Version Unknown' in General tab, and show only 1 interface ( the last interface of 'show system interface') in Interface tab. SNMP Location and Contact are normal.

**Comment by SCadilhac** [comment]
What FortiOS version are you running? VDOM enabled or not?

**Comment by wanghy124** [comment]
v6.0.11 build0387 (GA), VDOM disabled.

**Comment by RGlintmeijer** [comment]
Same problem here. Seems to be an issue with the pager.

The command "get system status" returns data with a pager (--More--). The pager is successfully detected by Netshot, but only the last 'page' is being returned to the driver. The driver then searches for Version and Hostname on that last part of the command output, but this info is in the first part of the result.

A **temporary** workaround is to override the driver and change the line to:

`var status = cli.command("get system status | grep .");`

This disables the pager in the output, so the driver can find the info again.

The real problem must be in the code that handles the the cli.command output with a pager.

**Comment by wanghy124** [comment]
> Same problem here. Seems to be an issue with the pager.
> 
> The command "get system status" returns data with a pager (--More--). The pager is successfully detected by Netshot, but only the last 'page' is being returned to the driver. The driver then searches for Version and Hostname on that last part of the command output, but this info is in the first part of the result.
> 
> A **temporary** workaround is to override the driver and change the line to:
> 
> `var status = cli.command("get system status | grep .");`
> 
> This disables the pager in the output, so the driver can find the info again.
> 
> The real problem must be in the code that handles the the cli.command output with a pager.

RGlintmeijer is correct. I also changed the line var showSystemInterface = cli.command("show system interface | grep ."). Everything works fine now. Thanks.

**Comment by SCadilhac** [comment]
Thanks, should be fixed now - ac0b2ff3932982aef4921756fa56d22c5ad266aa and 3e26f872a0e38ea3c33347ebb8665bda9035663a
