### ISSUE TITLE
Custom KV per device ?

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#128]
Hello.

I am looking for a way to store custom key/value per device (typically to store the "role" of the device or the configuration context from netbox associated to the device ( https://netbox.readthedocs.io/en/stable/models/extras/configcontext/ ) so I know which ntp/tacacs server this device should point to.

I was thinking to use diagnostics to do that (so the diagnostics would basically be a python/js script that will pull the values from netbox), is there a better alternative at doing this ? (a way to push those values from API calls?)

Thanks

**Comment by SCadilhac** [comment]
Indeed diagnostics are the only option at the moment.

**Comment by kedare** [comment]
However it looks like the python scripts cannot do external requests thru http.client for example, I am getting this error `ImportError: Cannot run any C extensions because native access is not allowed.`.

Can it be done with JS ? What would be the way to do it ?
Thanks
