### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by orgitnized** [netfishers-onl/Netshot#13]
Not sure that I mark this as being an issue, but working with a date format of [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) would be very much appreciated.  My brain cannot wrap my head around using DD-MM-YY in your app.  Can we please have an option to change this?  If the option exists, can you please tell me where it is?
Thanks!

**Comment by SCadilhac** [comment]
Dates are now displayed based on browser locales (54e06b54f2bca7e6f6b62f2b8a50e7eb532d2028)
