### ISSUE TITLE
How to export Device access failures report

### ISSUE THREAD

**Issue by uchihaitachi2** [netfishers-onl/Netshot#131]
Hi,
Is there a way to export the Device access failures report?
I want to verify if the snapshots are working fine, and I think that this report can give an idea abou the last successful snapshot.
If it is not possible to export this report, could you please tell on which  sql table does netshot stores these informations?
Thanks

**Comment by pizu** [comment]
hi @uchihaitachi2 

![image](https://user-images.githubusercontent.com/7047326/117170103-00010d00-adca-11eb-88b0-1f791afff43c.png)

**Comment by uchihaitachi2** [comment]
Hi @pizu 

I know, but I need to export the result as excel file...

Thanks

**Comment by uchihaitachi2** [comment]
Hello,
If it is possible, could you please tell me which sql tables does contains Device Access failures information?
Thank you!

**Comment by Rikharms1972** [comment]
I use a Python script for this:
- get device failures with REST-API.
- use xlsxwriter module to create excel file

 to test:  curl -X GET "https://{SERVER}/api/reports/accessfailuredevices?days=6" -H  "accept: application/json"

**Comment by uchihaitachi2** [comment]
@Rikharms1972, thanks for your reply
Could you please share the python script?
Thank you!

**Comment by Rikharms1972** [comment]
Sure, you can use this:

import requests
import urllib3
urllib3.disable_warnings()
netshot_user = ''
netshot_pass = ''
server = "<SERVER>"

login_url = f'https://{server}/api/user'

netshot_session = requests.Session()
payload = {'username': netshot_user, 'password': netshot_pass}
k = netshot_session.post(login_url, json=payload, verify=False)
k.raise_for_status()

accessfailuresurl = f'https://{server}/api/reports/accessfailuredevices?days=7'
accessfailuresget = netshot_session.get(accessfailuresurl)
accessfailures = accessfailuresget.json()



When you have the failures as a json dictionary, you can access the items, ie

for lines in accessfailures:
	print(lines['name'])

**Comment by uchihaitachi2** [comment]
Thank you @Rikharms1972
