### ISSUE TITLE
FortiAnalyZer (ForiOS) is it supported?

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#134]
Hi,

Am not sure if the FAZ (FortiAnalyzer) is supported or not - OS is FortiOS too.

Debug log attached.
[debug_959210.log](https://github.com/netfishers-onl/Netshot/files/6461356/debug_959210.log)

Thanks.

**Comment by Najihel** [comment]
I have just created PR for this : https://github.com/netfishers-onl/Netshot/pull/312
