### ISSUE TITLE
Upgrade From 0.15.2 to 0.16.0 error

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#136]
Hi,

Am having an issue after upgrading.

I followed: https://github.com/netfishers-onl/Netshot/wiki/Installing-Netshot-0.16-or-more-recent-on-Linux-server

![image](https://user-images.githubusercontent.com/7047326/118671505-d0a1c580-b7f7-11eb-89f3-74e7ea5fd42d.png)
![image](https://user-images.githubusercontent.com/7047326/118671673-f7f89280-b7f7-11eb-9480-6e13a09f98cf.png)

May 18 16:35:21 nettools01.corporate.intra java[12765]: Error: A JNI error has occurred, please check your installation and try again
May 18 16:35:21 nettools01.corporate.intra java[12765]: Exception in thread "main" java.lang.UnsupportedClassVersionError: onl/netfishers/netshot/Netshot has been compiled by a more recent version 
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.lang.ClassLoader.defineClass1(Native Method)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.security.AccessController.doPrivileged(Native Method)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
May 18 16:35:21 nettools01.corporate.intra java[12765]: at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
May 18 16:35:21 nettools01.corporate.intra systemd[1]: netshot.service: main process exited, code=exited, status=1/FAILURE
May 18 16:35:21 nettools01.corporate.intra systemd[1]: Unit netshot.service entered failed state.
May 18 16:35:21 nettools01.corporate.intra systemd[1]: netshot.service failed.

Can someone help please?

**Comment by SCadilhac** [comment]
You should run Netshot 0.16.2 rather than 0.16.0.
Despite your `java -version` output, it seems that the JRE version as called from the systemd unit is  < 11.

**Comment by pizu** [comment]
Hi,

after a reboot it worked however the drivers are not working :(

Screenshot attached below.

![image](https://user-images.githubusercontent.com/7047326/122050269-979f4580-cde3-11eb-8cb7-3b8a1671b01a.png)

![image](https://user-images.githubusercontent.com/7047326/122050391-b6054100-cde3-11eb-928b-5c0e7d9b0fd1.png)

**Comment by pizu** [comment]
version 0.16.2

**Comment by pizu** [comment]
did sudo /usr/lib/jvm/graalvm/bin/gu install python and worked.. sorry for any misunderstanding closing the issue.
