### ISSUE TITLE
networkClass issue of custom driver

### ISSUE THREAD

**Issue by wanghy124** [netfishers-onl/Netshot#137]
Hi team,

I write a new driver for Cisco Wiressless Controller. It work normally but below error output in task status.

```[ERROR] Can't add device attribute networkClass: No enum constant onl.netfishers.netshot.device.Device.NetworkClass.WIRELESS CONTROLLER```

I configured networkClass as ```device.set("networkClass", "WIRELESS CONTROLLER");``` in driver.
It looks like networkClass cannot be customized and no class "WIRELESS CONTROLLER" in Netshot? Also i will try to add Access point into Netshot.

**Comment by SCadilhac** [comment]
The defined classes are there: https://github.com/netfishers-onl/Netshot/blob/c4a9bfb1ad7a1493b87d9a29bc9c06170859032c/src/main/java/onl/netfishers/netshot/device/Device.java#L101
We can consider adding something for Wireless-related devices.

**Comment by wanghy124** [comment]
Hi SCadilhac,

Thank you very much.
