### ISSUE TITLE
Upgrade from 0.7.2 to 0.8.1

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#14]
Hi,

Are there any steps to Upgrade from 0.7.2 to 0.8.1?

Thanks,
David

**Comment by pizu** [comment]
Managed to do the upgrade but the version of the drivers didn't upgrade.

**Comment by SCadilhac** [comment]
There shouldn't be any specific step for these versions. Just replace `netshot.jar` and restart.
The instructions are there: https://github.com/netfishers-onl/Netshot/blob/master/dist/UPDATE.txt
Note: Not all the drivers have changed between the two releases.

**Comment by pizu** [comment]
Thanks for the reply.

am having the below errors after the upgrade.

[05] Snapshot task for device OTV_EDGE (xxxx).
[03] Device logs (1 next lines):
[1] The configuration hasn't changed. Not storing a new one in the DB.
[03] Error while taking the snapshot: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [onl.netfishers.netshot.device.Device#24]
[03] Device logs (1 next lines):
[1] The configuration hasn't changed. Not storing a new one in the DB.

**Comment by pizu** [comment]
Yes found :)

did the changes are recommended between version of 0.7.1 and 0.7.2.

**Comment by pizu** [comment]
as per commit 3f0af6c the version of the cisco ios is 1.6.1, mine is still 1.6 event after driver reload and full server reload.

![image](https://user-images.githubusercontent.com/7047326/41585887-9a9984fc-73ab-11e8-9818-5cc11f1f6083.png)

any idea what I might did wrong?

**Comment by SCadilhac** [comment]
Commit 3f0af6c is not integrated yet in an "official" release. Netshot 0.8.1 was packaged before that commit.
You can still install manually the last version of the driver manually: download the .js file, and place it into `/usr/local/netshot/drivers`. Then click the _Reload the drivers_ button in the _Admin_ tab.
You'll  delete the file when you install a future release which directly integrates the last changes of the driver.

**Comment by pizu** [comment]
ohh :)

Thanks. Everything seems to be working fine then :)
