### ISSUE TITLE
netshot error after deleting a switch and an snmp community

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#145]
[error.txt](https://github.com/netfishers-onl/Netshot/files/6853484/error.txt)

Hi,

After deleting an snmp community and a switch netshot got very slow, almost unable to work with, did a restart of the service and went back to normal.

Thanks.

**Comment by SCadilhac** [comment]
Are you able to reproduce the issue?

**Comment by pizu** [comment]
Will try to replicate the issue and record my screen.

**Comment by pizu** [comment]
was not able to replicate :(, can we keep the ticket open for now? just in case it happens again.

Thanks.

**Comment by SCadilhac** [comment]
Please re-open if needed.
