### ISSUE TITLE
Fortigate backups - 1500D model issue (v0.16.3)

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#146]
[INFO] Snapshot task for device GOFWMosta (172.16.60.250).
[ERROR] Error while taking the snapshot: Couldn't open either SSH or Telnet socket with the device.
[INFO] Connected using SSH to 172.16.60.250:0 using credentials admin_FG1500D.
[ERROR] Error while running snapshot using driver FortinetFortiOS: 'TypeError: Cannot read property 'replace' of null'.
[DEBUG] Unable to open an SSH socket to 172.16.60.250:0: TypeError: Cannot read property 'replace' of null

**Comment by pizu** [comment]
logs https://pastebin.com/fSEMgUp7

**Comment by SCadilhac** [comment]
Do you have SCP enabled to retrieve the config? See https://kb.fortinet.com/kb/documentLink.do?externalID=FD43754
Otherwise, the fallback should work with driver version 5.1 just fixed.

**Comment by pizu** [comment]
Hi @SCadilhac 
you're right, just enabled it from the global and now it worked. I will wait for the next version for the 5.1, so for am very happy with this version, I can see all the configuration now (as far as I know :))

config system global
 set admin-scp enable
end

Thanks,
