### ISSUE TITLE
Authentication error after clean install

### ISSUE THREAD

**Issue by JohannesJacobusvrmr** [netfishers-onl/Netshot#147]
Hi,

Just downloaded and installed netshot, nothing has been done since the setup of the database but the default account is not working with netshot/netshot.

Can I please get my moneys back?

Kr Joja V

**Comment by JohannesJacobusvrmr** [comment]
i can send the full install log if desired.

**Comment by SCadilhac** [comment]
Please refer to https://github.com/netfishers-onl/Netshot/wiki/Installing-Netshot-0.16-or-more-recent-on-Linux-server
The default account is `admin`, password `netshot`.

**Comment by JohannesJacobusvrmr** [comment]
Thanks @SCadilhac 

In the user guide: 

'**Main interface**
Netshot is available through a Web application GUI.

First you have to authenticate. The authentication settings must have been defined by the administrator. If nothing has been done since the setup of the database, the default account is _netshot/netshot._'

[https://github.com/netfishers-onl/Netshot/wiki/Netshot-User-Guide](url)

**Comment by SCadilhac** [comment]
Updated. Thanks.
