### ISSUE TITLE
Add comment/details field in the /api/reports/groupconfignoncompliantdevices endpoint

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#149]
Hello.

Currently the `/api/reports/groupconfignoncompliantdevices` endpoint doesn't include the potential comment/details added when doing the rule, we have to run a query on each device `/api/devices/xx/complianceresults`
It's not very clear in the code how the fields are defined on the API (does it automatically returns all the fields from the SQL query?) also would that required an update on the frontend code too not to break it ?

Thanks

**Comment by SCadilhac** [comment]
https://github.com/netfishers-onl/Netshot/blob/master/src/main/java/onl/netfishers/netshot/rest/RestService.java#L6230
The endpoint callback is here; the result is whatever this function returns.
