### ISSUE TITLE
Cancel and/ Edit Schedules.

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#15]
Hi,

Is this possible? I cannot anything :(

Thanks.

**Comment by pizu** [comment]
am asking as after the upgrade i noticed the below..

![image](https://user-images.githubusercontent.com/7047326/41663580-1033f618-74a4-11e8-956f-f2cbaed782f4.png)

**Comment by SCadilhac** [comment]
The duplication of the scheduled tasks looks like a bug. It will require an investigation.
For now, you can click on the 2nd button from the right, at the end of the row, in order to cancel the unwanted scheduled tasks.

**Comment by pizu** [comment]
I managed to clean them.. over 200 :(

Thanks for the reply and for doing the investigation.

**Comment by SCadilhac** [comment]
This issue seems to be caused by an upgrade, couldn't reproduce it with the latest versions.
