### ISSUE TITLE
Create documentation for docker-compose. 

### ISSUE THREAD

**Issue by nathantabailey** [netfishers-onl/Netshot#152]
After installing a few times via docker-compose, other people may benefit from the creation of a how-to doc in the wiki. This specific issue may also be resolved by storing the latest image on docker hub. 

`docker-compose up ` 

Fails because the image is not available on docker hub and needs to be built first.  Here are the required steps. 

```
git clone <repo> 
cd Netshot
docker build -t netshot:latest .
docker-compose up. 
```

**Comment by SCadilhac** [comment]
Thanks for the suggestion. I started a basic page: https://github.com/netfishers-onl/Netshot/wiki/Running-Netshot-in-Docker
Feel free to contribute for more details.
