### ISSUE TITLE
Updated Dockerfile after running into "Corrupted STDOUT by directly writing to native stream in forked JVM"

### ISSUE THREAD

**Issue by abaretta** [netfishers-onl/Netshot#159]
Hi Team,

FYI, I wanted to check out the Netshot docker version (looks great btw!), however the attempt to build it failed with a Java related error ("Corrupted STDOUT by directly writing to native stream in forked JVM"). It seems the issue is resolved or at least does not occur when using java11-21.3.0. With the Dockerfile below the build completed successfully.

```
FROM ghcr.io/graalvm/graalvm-ce:java11-21.3.0 as builder
COPY . /opt/netshot
WORKDIR /opt/netshot
RUN gu install python
RUN ./mvnw package


FROM ghcr.io/graalvm/graalvm-ce:java11-21.3.0
RUN gu install python
RUN mkdir /usr/local/netshot /var/log/netshot
COPY --from=0 /opt/netshot/target/netshot.jar /usr/local/netshot/netshot.jar
COPY dist/netshot.conf.docker /etc/netshot.conf
EXPOSE 8080
CMD ["/usr/bin/java", "-jar", "/usr/local/netshot/netshot.jar"]
```

**Comment by SCadilhac** [comment]
Thanks, I've updated the file as 21.3.0 is the target version anyway.
