### ISSUE TITLE
Error when purging old entries from the database

### ISSUE THREAD

**Issue by Rikharms1972** [netfishers-onl/Netshot#160]
Hello,

When I trie to purge old database entries it fails on configs I get an error:

[INFO] Cleaning up tasks more than 30 days ago...
[INFO] Cleaning up done on tasks, 0 entries affected.
[INFO] Cleaning up configurations older than 30 days...
[ERROR] Error during the configuration purge.

the table "long_text_configuration.ibd" is 48G large

Any Idea how I can fix this problem?

Thanks.

**Comment by arjanoosting** [comment]
I have debugged this issue a little further and the code in src/main/java/onl/netfishers/netshot/work/tasks/PurgeDatabaseTask.java seems to be incorrect.

At line 184 there the when parameter is set to the when variable which is an GregorarionCalenda object. 
The when parameter should be set to when.getTime() which gets the corresponding Date object of the Calendar object.

(At line 116 another query gets the when parameter in the correct way with an when.getTime() call)
