### ISSUE TITLE
API devices search endpoint return the same host multiple times

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#163]
I am hitting a strange issue on the `/api/devices/search` endpoint, when searching with an IP like `[IP] IS 1.2.3.4`, the endpoint returns a single device but multiple time.

Is this expected or a bug ?

Exemple of response :

```
{
  "query": "[IP] IS 1.2.3.4",
  "devices": [
    {
      "id": 2318,
      "name": "my-device",
      "family": "Cisco Catalyst 2900",
      "mgmtAddress": {
        "prefixLength": 0,
        "addressUsage": "PRIMARY",
        "ip": "1.2.3.4"
      },
      "status": "INPRODUCTION"
    },
    {
      "id": 2318,
      "name": "my-device",
      "family": "Cisco Catalyst 2900",
      "mgmtAddress": {
        "prefixLength": 0,
        "addressUsage": "PRIMARY",
        "ip": "1.2.3.4"
      },
      "status": "INPRODUCTION"
    }
  ]
}
```

The amount of returned identical device is not fixed sometime it's just 1 as expected and sometime I get more than 20 identical ones.

**Comment by SCadilhac** [comment]
This will happen if the queried IP address is found in multiple interfaces (or is the management IP address).
But this doesn't sound normal, so cb3a528f4c298aa49b3c931e0fde946a74f7129b should fix it.
