### ISSUE TITLE
Netshot version 0.16.3 device deletion and API issue

### ISSUE THREAD

**Issue by zholbrook** [netfishers-onl/Netshot#164]
When onboarding three devices 1, 2 and 3 everything works fine. I hit the API and I get the proper ID's and can use the IDs to get configs.

However I deleted device 2 from the netshot UI, and in the UI it still shows I have device 1 and 3 and when I hit the API and getDevices I show ID's 1 and 3.

But when I try to get configs for devices 1 and 3 the configs seemed to have moved to ID's 1 and 2.

**Comment by zholbrook** [comment]
Testing some more, I now have a device 1 and device 5. When I Run the getDevices from the API it returns "id" 1 and 5 but when I try to get the runningConfig it is stored under "id" 1 and 4.

**Comment by zholbrook** [comment]
This may be because when I tried to onboard device 2 it failed due to credential issue but then device 3 onboarded fine. Im deleting everything and starting over to verify.

**Comment by zholbrook** [comment]
Should I net be able to get the device ID and then use that to get the config ? If not please help guide me.

**Comment by zholbrook** [comment]
`[
    {
        "id": 1,
        "name": "router 1",
        "family": "Cisco Catalyst 6800",
        "mgmtAddress": {
            "prefixLength": 0,
            "addressUsage": "PRIMARY",
            "ip": "10.101.3.0"
        },
        "status": "INPRODUCTION"
    },
    {
        "id": 5,
        "name": "router 5",
        "family": "Cisco Catalyst 3850",
        "mgmtAddress": {
            "prefixLength": 0,
            "addressUsage": "PRIMARY",
            "ip": "10.101.3.1"
        },
        "status": "INPRODUCTION"
    }
]`



when getting the config /api/configs/5/runningConfig give no config
/api/configs/4/runningConfig provides the config for router 5

**Comment by SCadilhac** [comment]
`GET /api/devices/<id>/configs` to get the config IDs for that device

**Comment by zholbrook** [comment]
Yea, thats why im saying. In my example I have an id of 1 and 5 but when I try to get the device config its not there. I have to use ID 4

when getting the config
 /api/configs/5/runningConfig give no config
/api/configs/4/runningConfig provides the config for router 5

This occurred after deleting device 2, before this the numbers matched properly. Now it seems they are all -1 off like device 6 is config id 5 and so on.

**Comment by SCadilhac** [comment]
Config IDs are not the same as device ID. For a given device ID, retrieve first the config list, and then for the config ID you can retrieve the item you need.

**Comment by zholbrook** [comment]
Ok, I see now. Thanks!
