### ISSUE TITLE
device search options

### ISSUE THREAD

**Issue by zholbrook** [netfishers-onl/Netshot#167]
What are my device search options, Below is my current post with the IP being the variable, but for some reason my newly onboarded devices are not searchable via IP.

So:
1. Why is my freshly onboarded device not available via search, is there a schedule test of somekind?
2. What are my other query options?

{
    "query": "[IP] IS 10.1.1.1"

}

**Comment by SCadilhac** [comment]
The query returns nothing until the interfaces have been discovered (in the first snapshot). This needs to be improved.

When you add the device, the API should return the task details, which contain `deviceId`, you can use this to find the device.

**Comment by zholbrook** [comment]
Is there a workaround to get the search to work? I have tried to delete/readd that doesnt seem to work, but If i click on the interfaces tab I do see the devices interfaces. I have built my current workflow around the search working. If not i will have to refactor. Thanks!

**Comment by SCadilhac** [comment]
The mentioned commit should fix the issue where you search for devices with no discovered (yet) interface.
If interfaces are properly discovered already, then I'm surprised it's not working... it means that you get no device when you enter the target IP address in the search box within the Web UI?

**Comment by zholbrook** [comment]
I will give the new version a try but I did verify my 2 devices that I cannot search for do have interfaces populated when I click the interfaces tab for that device. It's also pulling in the interface modules.

**Comment by zholbrook** [comment]
This did fix the search issue, thanks!
