### ISSUE TITLE
HTTPS Certificate.

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#17]
Hi,

Is it possible to change the HTTPS Certificate? As we would like to generate our own certificate.

**Comment by SCadilhac** [comment]
Yes sure. If you followed the standard procedure to install Netshot, you created a self-generated certificate as a keystore file called `/usr/local/netshot/netshot.jks`. You can generate your own certificate by other means and import it in a new keystore file.
See https://docs.oracle.com/cd/E35976_01/server.740/es_admin/src/tadm_ssl_convert_pem_to_jks.html for example.
