### ISSUE TITLE
API Task Subnet Scan

### ISSUE THREAD

**Issue by zholbrook** [netfishers-onl/Netshot#170]
Following https://www.netfishers.onl/blog/2015/07/14/use-the-netshot-api-to-scan-a-subnet-of-devices

Is there a way in the Post to specify to use SSH credentials? Every box on my network has different snmp words so ssh is preferred.

**Comment by zholbrook** [comment]
Any ideas on this?

**Comment by SCadilhac** [comment]
If you have specific SSH credentials for each device, don't use subnet scan task, but rather call the device creation endpoint for each device.

`POST /api/devices`
```json
{
  "name": "MyNewDevice",
  "ipAddress": "192.168.192.168",
  "autoDiscover": false,
  "deviceType": "CiscoIOS12",
  "domainId": "1",
  "autoDiscoveryTask": -1,
  "specificCredentialSet": {
    "type": "SSH",
    "name": "",
    "username": "admin",
    "password": "cisco",
    "superPassword":"cisco"
  }
}
```

**Comment by zholbrook** [comment]
this works, closing
