### ISSUE TITLE
Scripts menus idea.

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#171]
Hi,

Is it possible to have a drop-down menu for scripts?.

I'd like to prepare multiple scripts to be ready to use, for example, password change script. Usually, if we do a password change it's going to be on a good number of devices. Would be nice also to have the script to run on multiple devices at once by choosing a group.

Thanks.

**Comment by momolemo** [comment]
hi,
you can run a prepared script on multiple devices.
first you have to save a script. open a device with the driver you want. write the script and save it with the arrow on the left.
now You just have to select multiple devices on the left panel (witch ctrl) and select run a script.
you choose which drivers to use, so if you select device of another driver the script will not execute on this one. (netshot guarantee that you run a script only on one type of device)
You can now load a prepared script with the arrow on the left of the script windows.

enjoy :)
