### ISSUE TITLE
feature request: diff context

### ISSUE THREAD

**Issue by seros1521** [netfishers-onl/Netshot#174]
When displaying the differences between two backups, only the changed lines and several adjacent ones are displayed. But this is not enough to understand where the change took place. For example, if you turn off the interface, the surrounding lines will be visible, but the name of the interface may not be there: 
![изображение](https://user-images.githubusercontent.com/55374617/144713740-a1378f55-f7e4-459e-870b-678bc2bf3058.png)

I would like to see something like this (`diff -u --show-function-line='^[^ ]' b1.txt b2.txt` or `diff -u -F '^[^ ]' b1.txt b2.txt`): 
```
@@ -217,6 +217,7 @@ interface FastEthernet0/5
  switchport mode access
  switchport nonegotiate
  switchport voice vlan 60
+ shutdown
  priority-queue out
  ipv6 nd raguard
  storm-control broadcast level 3.00
```
here you can see the name of the block in which the changed line is located.

The definition of the context can be different for different types of devices. It may be worth allowing some configuration parameter at the device driver level (and default value) in order to allow different behavior. It depends on the capabilities of the library used to generate the diff. In complex cases with high nesting of elements, the capabilities of the library for generating the list of differences may not be enough, then it would be useful to set a function in the driver that accepts the entire configuration and the target line number and returns the context value (configuration blocks separated by commas or in another format). A universal algorithm suitable for most would be the following:
1. for an arbitrary line, the block name is a configuration line with a lower indentation level than the current one.
2. repeat finding the parent block until the indent is 0
3. merge the contexts of the higher blocks.

**Comment by SCadilhac** [comment]
I added simple indentation-based hierarchy context to the diff view in cc0fb59f11017c5e38c0c0249d4fa5cd3eccc944

Example:
![image](https://user-images.githubusercontent.com/14115661/150693604-af4d24d2-124f-4201-9c13-c3412230282c.png)

**Comment by seros1521** [comment]
Ideally. The best I've ever hoped for. Great thanks.
