### ISSUE TITLE
feature request: Add option to use diagnosics in javascript based compliance rules

### ISSUE THREAD

**Issue by Rikharms1972** [netfishers-onl/Netshot#180]
Hello,

When creating a text rule you can check on a diagnostic (Field to check pull down).
I would like to have the possibility to do the same when using javascript based compliance rules.
Is this possible?

Thanks,
Rik

**Comment by SCadilhac** [comment]
You should be able to retrieve the last diagnostic result from the compliance script using `device.get(name)` where `name` is the diagnostic name.

**Comment by Rikharms1972** [comment]
Awesome. so simple, but oulc not finut myself :-). Just testd it and it works prefect.
Thanls for helping me out.
