### ISSUE TITLE
Cisco_IOS.js driver issue password prompt

### ISSUE THREAD

**Issue by Rikharms1972** [netfishers-onl/Netshot#182]
Hello,

I have an issue with the Cisco_IOS driver.
When I take a snapshot, some older cisco devices fail on macro (auto)

When I remove the space on line with password it all works.
So original line 112:
prompt: /^[Pp]assword: $/,

I change to :
prompt: /^[Pp]assword:\s?$/,

and it works.

Can this be verified and if possible be updated in the driver?
Thanks

**Comment by SCadilhac** [comment]
Could you submit a PR? And increment the driver version number.
