### ISSUE TITLE
Data export problem - Netshot version 0.17.0?

### ISSUE THREAD

**Issue by cianv** [netfishers-onl/Netshot#187]
Hi, I'm testing this tool (Netshot version 0.17.0) and so far it works great.
The only thing that doesn't work is the data export. I'm getting "http error 500".
Is there something special that I have to enable or?

Thank you in advance!

**Comment by SCadilhac** [comment]
Can you check logs (`/var/log/netshot/netshot.log`) on the server for the error message?

**Comment by cianv** [comment]
[netshot.log](https://github.com/netfishers-onl/Netshot/files/8032291/netshot.log)
Log is attached

**Comment by cianv** [comment]
I've noticed that there is this error message;
_"ERROR [grizzly-http-server-6] RestService: Uncaught exception thrown by REST service
java.lang.InternalError: java.lang.reflect.InvocationTargetException"_

And that might be the problem with the java version
This is the output from server regarding the java and it's the same that is in the installation procedure
_"java -version 2>&1 | grep Environment | grep GraalVM
OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)"_

Maybe there is some issue with permissions?

**Comment by SCadilhac** [comment]
Looks like the server is rather missing a font package (`freetype`, `fontconfig`, `dejavu-sans-fonts`).
