### ISSUE TITLE
Issue with snapshot Junos driver

### ISSUE THREAD

**Issue by Rikharms1972** [netfishers-onl/Netshot#189]
Hi,

I just added a new Juniper router and the snapshot fails with this error:

[INFO] Snapshot task for device [NONAME] (172.27.217.35).
[INFO] Connected using SSH to 172.27.217.35:0 using credentials RSA_SSH_NETSHOT.
[ERROR] Can't add device attribute networkInterface: Unable to parse the IPv4 address
[INFO] The configuration has been saved as a file in the dump folder.
[ERROR] Error while taking the snapshot: org.hibernate.exception.GenericJDBCException: could not execute statement
[INFO] Connected using SSH to 172.27.217.35:0 using credentials RSA_SSH_NETSHOT.
[ERROR] Can't add device attribute networkInterface: Unable to parse the IPv4 address
[INFO] The configuration has been saved as a file in the dump folder.

I`m using the 2.13 JuniperJunos driver and I can`f figure out what is going wrong. I have other Juniper wich work fine. so I assume something in the config is causing the driver to fail.

Thanks,
Rik Harms

**Comment by Rikharms1972** [comment]
[log.txt](https://github.com/netfishers-onl/Netshot/files/8061277/log.txt)

**Comment by SCadilhac** [comment]
There seem to be unsupported characters collected by the driver which fail to be inserted into the DB.
`'\xC2\x96 UPC...'`
You should check the descriptions and other free-form strings in the device configuration. You may also want to double check the default encoding and charset of the underlying database. Maybe time to migrate to PostgreSQL.

**Comment by Rikharms1972** [comment]
Thanks, I found a bug in my junipers. It turned out the codig was wrong in some descriptions. thya matched 'UPC' while it was ni in the descriptions. By re applyuing the descriptions it worked.

**Comment by Rikharms1972** [comment]
thanks
