### ISSUE TITLE
Use CLI function at compliance

### ISSUE THREAD

**Issue by sonpd2** [netfishers-onl/Netshot#194]
Can you show me how to use CLI function at compliance to run some command and return value for check compliance

**Comment by SCadilhac** [comment]
You have to declare a _diagnostic_, and then create a compliance rule based on the diagnostic result.

**Comment by sonpd2** [comment]
Awesome, Can you show me the guideline or example to make it. I can't find it at https://github.com/netfishers-onl/Netshot/wiki/User-Guide:-Compliance
