### ISSUE TITLE
SNMPv3 issue

### ISSUE THREAD

**Issue by Rikharms1972** [netfishers-onl/Netshot#199]
I have an issue with SNMPv3 discovery.
- I have two SNMPv3 entrys created for one domain.
- when I start a discovery it starts with entry1.
- But if entry 1 is not configured on the netwirk device (IOS-XR) it give back: "Unknown user name"
- (At least whit an snmpwalk:  Unknown user name)
- It does not move on to entry 2 and in the end is it set as a generic device.

Is it possible to consider this as a "no response"and trigger the next entry and at the and return failed?

Thanks

**Comment by SCadilhac** [comment]
458ab7efa84887b6972b414bff5635b711c2bb33 should help.
