### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by sajaltiwari** [netfishers-onl/Netshot#20]
Hi,
Can we an option of searching a specific keyboard(for ex: IP Address,VLAN) in the config backup of all the devices.

**Comment by SCadilhac** [comment]
You can find devices whose configuration contains a specific string: click the button to open the _Advanced search_ dialog, select the type of equipment (Cisco IOS for example), and select _Running configuration_ in the list of available fields. You can build a query like:
`[Running configuration] CONTAINS "something"`
Netshot will find the matching devices, but, in the current version, won't show you the context of the search results.
