### ISSUE TITLE
Information about the docker implementation

### ISSUE THREAD

**Issue by Trasmontinho** [netfishers-onl/Netshot#202]
Hi Sylvain, 

I was looking about informations regarding the Docker implementation and particularly the docker compose implementation. 

How the variables in the Netshot container are loaded into the container ? 

What are the variables authorized into this implementation ? 

Is there any documentation about it ? 

Thanks for your answers. 

Regards, 

Sam

**Comment by SCadilhac** [comment]
Hello,

Very short guide here: https://github.com/netfishers-onl/Netshot/wiki/Running-Netshot-in-Docker
As you can see in Dockerfile, dist/netshot.conf.docker is used as configuration file in the container.
Moreover, Netshot (0.16+) supports environment variables to override config properties. See https://github.com/netfishers-onl/Netshot/wiki/Config-file-(netshot.conf)-reference
