### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by eczema** [netfishers-onl/Netshot#21]
Hi,

First of all, thanks for this really nice tool. You did a really nice job.
As I have to use Postgresql, I did some test by changing the jdbc driver and uri.

This doesn't work for multiple reasons....

First one  quite easy to fix , is the varchar size used into java code: 10GB... This size is too big , so changing to 1G is working. 

I continue to investigate how to resolve remaining issue and will keep you informed.  

I will try to find proper way to not break anything for users using mysql or having a install already in activity.... 

Kind regards,

Alain

PS: A new Compile howto could be a nice to have.... I found that all was done with Maven due to pom.xml  but I'm not sure that anybody will be able to compile the project from source....

**Comment by SCadilhac** [comment]
Hi @eczema,

Thanks for the work here. I've accepted the commits, and updated the installation file. I've updated the JDBC driver version as well.
Note that Netshot automatically creates the DB structure when starting.
