### ISSUE TITLE
Feature Request : increase comment size compliance check result

### ISSUE THREAD

**Issue by momolemo** [netfishers-onl/Netshot#214]
Hello,

The comment field of the compliance result is max 255, the database field is limited to varchar 255 and i see in the class checkresult you abreviatte it to 255.

Is it possible to increase this size because i return in the comment differences and i have on some switch too much diffence....

I search to do it by myself in the code but i dont really understand how i can do this.

Regards

**Comment by SCadilhac** [comment]
Done in ba6a81ac958cb0947995acbed430e2d0f8c427a5
