### ISSUE TITLE
[docker implementation]SNMP traps for config change not received by the netshot

### ISSUE THREAD

**Issue by Trasmontinho** [netfishers-onl/Netshot#222]
Hi @SCadilhac,

I've implemented the docker installation supplied in the wiki with some tweaks that are specific to my server.

below the diagram of my implementation : 

![docker_trap_issue](https://user-images.githubusercontent.com/53441739/177600242-ad21c597-90e0-4ecc-9804-f946e4153bb9.png)

the snmptraps are received from my eth0 interface. As the host had a old implementation of Netshot, NAT is implemented in the network interface like (define for a local installation) : 

```
iptables -t nat -D PREROUTING -p udp --dport 162 -j REDIRECT --to-port 1162
#iptables -t nat -D PREROUTING -p udp --dport 514 -j REDIRECT --to-port 1514
iptables -t nat -A PREROUTING -p udp --dport 162 -j REDIRECT --to-port 1162
#iptables -t nat -A PREROUTING -p udp --dport 514 -j REDIRECT --to-port 1514
```

For the communication with devices by SNMP, I haven't any problem to communicate whith the devices but the traps notifying changes are not arriving to the netshot container.

Below my netshot.conf.docker implementation and attached my docker-compose.yml.

```
# Netshot Configuration File
# See https://github.com/netfishers-onl/Netshot/wiki/Config-file-(netshot.conf)-reference

# Log file and level
netshot.log.file = CONSOLE
netshot.log.level = WARN
netshot.log.file = /var/log/netshot/netshot.log
netshot.log.audit.file = /var/log/netshot/audit.log
netshot.log.audit.level = INFO
#netshot.log.syslog1.host = 10.0.16.16

# Database connection
#netshot.db.driver_class = com.mysql.cj.jdbc.Driver
netshot.db.driver_class = org.postgresql.Driver
#netshot.db.url = jdbc:mysql://localhost/netshot01
netshot.db.url = jdbc:postgresql://localhost/netshot01
netshot.db.username = netshot
netshot.db.password = mypassword
# The following password is used to encrypt the passwords and communities in the database.
# Changing it will cause all device passwords and communities to be manually reentered within the application.
netshot.db.encryptionpassword = netshot

# REST
netshot.http.ssl.enabled = false
netshot.http.baseurl = https://0.0.0.0
netshot.http.baseport = 8085

# Embedded syslog server (to react upon configuration change on the devices)
#netshot.syslog.port = 1514

# Embedded SNMP trap receiver (to react upon configuration change on the devices)
netshot.snmptrap.port = 1162
netshot.snmptrap.community = Netsh01

# General settings
# Minimal Interval (in minutes) between two automatic snapshots
netshot.snapshots.auto.interval = 15
# Allow a trap received from any IP of a device to trigger an automatic snapshot
netshot.snapshots.auto.anyip = true
# After a snapshot, dump the last configuration to a file in this directory
netshot.snapshots.dump = /usr/local/netshot/configs
# Where to store the binary snapshot files
netshot.snapshots.binary.path = /var/local/netshot
netshot.tasks.threadcount = 20

# Where to look for additional drivers
netshot.drivers.path = /usr/local/netshot/drivers


# Connection settings
#netshot.cli.telnet.connectiontimeout = 5000
netshot.cli.ssh.connectiontimeout = 60000
```

If could give some help. I've tried to find some information by my side but with no answers. 

Thanks, 

Regards, 
Sam

[docker-compose.txt](https://github.com/netfishers-onl/Netshot/files/9056756/docker-compose.txt)

**Comment by Trasmontinho** [comment]
I've tried also to delete the NAT in the if-up.d folder and change the port to 162:1162 into the docker implementation but there's changes in the reception of the config changes. 

Regards, 

Sam

**Comment by SCadilhac** [comment]
You should indeed rely on Docker for the port translation, so the host receives traps on UDP/162 and forwards to the container UDP/1162.
You might want to check with `tcpdump` first thing if traps are indeed reaching the host running the container.

**Comment by Trasmontinho** [comment]
Hi @SCadilhac,

Thanks for your reply. After a new look on the implementation, and specifically on the iptables, I've seen that no packets where forwarded to the container. 

I've had a better look on the iptables and seen that even after commenting the lines on the iptable file placed on the if-up. There still are rules on iptables. 

I flushed the iptables nat rules, restarted the docker and have been able to see the "Automatic snapshot after config change" appears in the container. 

Thanks again for your support ! 

Regards,

Sam
