### ISSUE TITLE
Cisco - AP and WLC

### ISSUE THREAD

**Issue by pfunkylol** [netfishers-onl/Netshot#226]
Hi,

Any plans/roadmap to add drivers for network drivers for devices such as Cisco Access points and WLC ?

**Comment by SCadilhac** [comment]
Cisco autonomous APs still run IOS if I'm not mistaken?
First driver for WLC was just added to the repository.

**Comment by pfunkylol** [comment]
Hmm, to be honest I didnt try adding a AP to confirm this.
The WLC driver works like a charm, thank you.
