### ISSUE TITLE
Debug output for custom driver

### ISSUE THREAD

**Issue by w1tht0uchp4d** [netfishers-onl/Netshot#227]
Hello,

in the past there was the possibility to collect debug output from a custom driver by issuing a command in the .js file and using the "Debug full session" function while performing a snapshot. Unfortunately I can't remember the command nor can I find it in the documentation. I think it was something like cli.debug("Message") or console.debug("Message"). Could you update the Netshot documentation regarding this topic please?

**Comment by SCadilhac** [comment]
`cli.debug("Message");` in the driver should indeed do it. This is likely to change in the future.

**Comment by w1tht0uchp4d** [comment]
Thank you, that did do the trick.
