### ISSUE TITLE
forms control confusion...

### ISSUE THREAD

**Issue by eczema** [netfishers-onl/Netshot#23]
When using snaphot/compliance check or run script, if a I press "Start as soon as possible" , I can schedule the task but if I click on Save, the task runs directly... Is it the right behavior ?  

e.

**Comment by SCadilhac** [comment]
Nope, sounds like a bug, but I just made some testing and cannot see the issue.

**Comment by eczema** [comment]
For sure, but a bug of meaning ;-) . Code is totally ok. The problem is that I didn't understand imediatly the meaning of   "Start as soon as possible, run once" 

IMHO, showing directly the expended form is less confusing
