### ISSUE TITLE
Cisco IOS XR - diff every iteration

### ISSUE THREAD

**Issue by pfunkylol** [netfishers-onl/Netshot#230]
Hello,

I've noticed that for IOS XR devices, everytime a task runs it creates a new diff due to the command from below where the date/time is different at every run.
`var showInstall = cli.command("admin show install active");`

Is there a way to exclude the first line from being checked/pulled and not create a diff everytime ?

Regards,
Paul

**Comment by SCadilhac** [comment]
I don't have this issue.
The driver normally disables the default timestamps printed by IOS-XR CLI prior to each output: https://github.com/netfishers-onl/Netshot/blob/7d107cf93ab3cc52733a6356f70d130ac055851c/src/main/resources/drivers/Cisco_IOS-XR.js#L124
What time line do you see at your side? Is it specific to an XR version?

**Comment by pfunkylol** [comment]
Hi,

It's both in IOS-XR 7.1.3 and 6.7.3 , different ASR9k devices.

https://imgur.com/2lNJmM0

**Comment by SCadilhac** [comment]
Are you sure the user used by Netshot to connect to the router is allowed to execute the three `terminal` commands?

**Comment by pfunkylol** [comment]
I double checked at appeared that the user didnt had access to issue the last command.
It was fixed after it was provisioned access to execute it.

Thanks.
