### ISSUE TITLE
Cisco - Failing to take a snapshot : [ERROR] "Too many steps while switching to a new mode" 

### ISSUE THREAD

**Issue by idavidA** [netfishers-onl/Netshot#231]
Hello Sylvain,

I have installed netshot last week and I am getting an error when I add cisco devices ( F5 and Fortinet are working fine).
The discovery step with snmp is OK but the snapshot Task fails with the below error :
"[ERROR] Error while taking the snapshot: Too many steps while switching to a new mode"
I tried to add different types of cisco devices and IOS version and I get the same error for all of them.
-Cisco C9500 ( C9500-16X) - IOS-XE Version 17.3.1
-Catalyst 4500 ( WS-C4507R) - IOS Version 12.2(31)SGA10
-C3850 (WS-C3850-48P) - IOS-XE Version 16.6.4

**Device Discovery OK:**
_[TRACE] Trying SNMPv2c discovery.
[ERROR] Error while polling the device via SNMP.
[TRACE] Trying SNMPv2c discovery.
[ERROR] Error while polling the device via SNMP.
[TRACE] Trying SNMPv2c discovery.
[DEBUG] Got sysDesc = Cisco IOS Software [Amsterdam], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 17.3.1, RELEASE SOFTWARE (fc5)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2020 by Cisco Systems, Inc.
Compiled Fri 07-Aug-20 21:32 by mcpre
[DEBUG] Got sysObjectID = 1.3.6.1.4.1.9.1.2593_

**Device Snapshot NOK:**
_[INFO] Snapshot task for device [NONAME] (10.x.x.x).
[ERROR] Error while taking the snapshot: Too many steps while switching to a new mode.
[TRACE] Will try SSH credentials Cisco SSH.
[INFO] Connected using SSH to 10.x.x.x:0 using credentials Cisco SSH.
[ERROR] Error while running snapshot using driver CiscoIOS12: 'Too many steps while switching to a new mode.'._

Many thanks for your support.
Regards,
David

**Comment by SCadilhac** [comment]
That means the driver cannot find the IOS prompt. Do you have any customization of the prompt?
You may want to start snapshot in debug mode to see what's happening: https://github.com/netfishers-onl/Netshot/wiki/Snapshot-troubleshooting

**Comment by idavidA** [comment]
Hello Sylvain and thanks for your swift reply. Yes we do have a customized logon banner. 
Noted, I will run the snapshot in debug mode and try to find the issue and fix it.
Many thanks for your support.
David

**Comment by idavidA** [comment]
Hi Sylvain,

As per the debug file, it looks like it is failing after "enable" for a reason that I could not figure out.
Below is the prompt of one of our routers:

**login as: admin
Pre-authentication banner message from server:
| xxxxxxxxxxx
| *****************************************************************************
| ***                                                                       ***
| ***                              xxxxxxxxxxxxxxx                          ***
| ***                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ***
| ***                                                                       ***
| ***   Vous allez acceder aux systemes informatiques de xxxxxxxxxxxxxxx    ***
| ***      Les tentatives d'access illicites (meme infructueses) sont       ***
| ***                       passibles de sanctions penales                  ***
| ***                                                                       ***
| *** --------------------------------------------------------------------- ***
| ***                                                                       ***
| ***        Warning! - This system is the property of xxxxxxxxxxxxxxx      ***
| ***      Unauthorized or improper use of this system may result in        ***
| ***    administrative disciplinary action and civil criminal penalties    ***
| ***                                                                       ***
| *****************************************************************************
End of banner message from server
Keyboard-interactive authentication prompts from server:
| Password:
End of keyboard-interactive prompts from server

Router>en
Password:
Router#**

Many thanks for you help.
[debug_121.log](https://github.com/netfishers-onl/Netshot/files/9319677/debug_121.log)

**Comment by SCadilhac** [comment]
Looks like your device doesn't return space after `Password:` as Cisco IOS devices normally do. Are you using TACACS+?

**Comment by idavidA** [comment]
Ooooh is it ? Yes we are using TACACS+.

**Comment by SCadilhac** [comment]
So probably with TACACS+ you are return "Password:" as prompt without final space.

**Comment by idavidA** [comment]
Hi Sylvain,

You were right, the regex for the enable secret password expects a space whereas the one for the password handles both:

**password: {
		prompt: /^[Pp]assword:\s?$/,**

**enableSecret: {
		prompt: /^[Pp]assword: /m,**


I modified the code of CiscoIOS12 for enable secret prompt to : **/^[Pp]assword:\s?$/m** and it is working fine now.

Once again many thanks for your support.
David
