### ISSUE TITLE
Help needed driver Nokia DWDM 1830

### ISSUE THREAD

**Issue by Rikharms1972** [netfishers-onl/Netshot#238]
Hello,
I`m struggling with a driver for Nokia DWDM 1830 system. This device uses a non standard way of logging in:

###################START
ssh cli@testdevice
Last login: Thu Nov 10 23:59:18 2022 from 172.22.170.107
Linux EC1830-81-1 2.6.10_mvlcge401-8555-cplab #4 Tue Jan 29 13:00:45 EST 2019 ppc GNU/Linux

Welcome to MontaVista(R) Linux(R) Carrier Grade Edition 4.0 (0600995).

Username: admin
Password: 
Last Login: Mon Nov 07 14:52:34 2022 from ssh_172.22.170.107-35994

Security compliance warning - Please check password status! 

Nokia 1830 PSS, WAVELENGTH TRACKER
(c) 2019 Nokia.  All rights reserved.

   Legal Notices  applicable to  any  software   distributed  alone or in
   connection with the product to which this text pertains, are available
   at  NOS (Nokia Online Services)  with "1830  Photonic  Service  Switch
   (PSS) Software Legal Notice Details".

   This  system   is  restricted  solely to  Nokia  authorized  users for
   legitimate    business  purposes   only.    The actual   or  attempted
   unauthorized  access, use, or modification of this system  is strictly
   prohibited  by  Nokia.  Unauthorized  users  are  subject  to  Company
   disciplinary   proceedings and/or  criminal and  civil penalties under
   state, federal, or other applicable domestic and foreign laws.  Use of
   this  system may  be monitored  and  recorded for  administrative  and
   security reasons.  Anyone accessing this system expressly  consents to
   such  monitoring and is advised  that if  monitoring  reveals possible
   evidence of criminal activity, Nokia may provide  the evidence of such
   activity to law  enforcement  officials.   All  users must comply with
   Nokia   Corporate  Instructions  regarding  the  protection  of  Nokia
   information assets.

Do you acknowledge? (Y/N)?yes

Alarm Status:  Critical-1   Major-0   Minor-0 Warning-12

testdevice# 

###################END

I`m not able to create a driver that properly works. Hope you can help me in the right direction.

Thanks,
Rik

**Comment by SCadilhac** [comment]
You just need a transient prompt mode, which matches `/Do you acknowledge.../` and automatically sends `"y"` (using `auto` macro). You can refer to https://github.com/netfishers-onl/Netshot/blob/master/src/main/resources/drivers/Avaya_ERS.js driver (check `ctrly` CLI mode).

**Comment by Rikharms1972** [comment]
I have been playing for a while and I got it working. I used the username as first username. the password as second username and enable password as the password...
