### ISSUE TITLE
Find Folder Device Types (Drivers)

### ISSUE THREAD

**Issue by Stippa3** [netfishers-onl/Netshot#241]
Hi, 
I installed Netshot on Ubuntu. I need to add new Drivers to download configuration for Aruba, HP Brocade, and Mikrotik. 
In which folder can I find the existing Drivers inside the server? Is there a procedure or guide to add new Device Types?

Regards

Stefano

**Comment by bogdancordos** [comment]
Hi,
Fallow the instruction on this documentation page:
https://github.com/netfishers-onl/Netshot/wiki/Loading-an-alternative-driver-into-Netshot

**Comment by Stippa3** [comment]
Hi,
thanks for your help. Some people implemented Drivers for Aruba, HP Brocade, and Mikrotik? Is thereis a general file that I can modify depending on vendors?

Regards

Stefano
