### ISSUE TITLE
[BUG] python venv

### ISSUE THREAD

**Issue by momolemo** [netfishers-onl/Netshot#248]
Hello,

on netshot 0.18.2 we are trying to get python venv working to add more package. we are on graalvm 21.3.0 like the doc recommend.

We follow the doc and install netshot, working fine.
We have install python with the gu command provide in the install doc.
We have created the venv like the wiki page said.

When we use python venv from the command line we can import the package and use it but when we are triing to use it from a netshot compliance the package can't be find.

![image](https://user-images.githubusercontent.com/3429382/216073999-2c8d7d67-0fd7-44a3-b97c-1d1de7fa77b0.png)

do you have any idea of what we miss ? we have no clue why netshot try to load from /tmp....

Regards

**Comment by SCadilhac** [comment]
Did you try with the two security flags off in the config file as suggested in the doc?

**Comment by momolemo** [comment]
The bug in the capture is when the 2 flag are true.

When a set them to false i have another error:
"[ERROR] Error while running the script: ImportError: Cannot run any C extensions because native access is not allowed."
this one seems logical.

I dont understand where he find this path with tmp. There is nothing in it and and don't find any reference to this path in the venv.

regards

**Comment by momolemo** [comment]
I update my case...
The flags need to be exactly
netshot.python.allowallaccess = true
netshot.python.filesystemfilter = false

With the lot of test i made for différents problem i change the value and set the two to true so i active the filesytemfilter.
Sorry for this... 
Now i have not the error on this import so it is better. But i cannot use requests module. i now have the error :
`[ERROR] Error while running the script: org.graalvm.polyglot.PolyglotException: ConnectionError: <class 'MaxRetryError'>`

Is there limitation on the graalpython which can lock the use of network call like requests?

**Comment by momolemo** [comment]
I close this issue, after some tests venv is working but with limitation from graal. All package cannot working.
il wiil work differently.
thanks for your response
