### ISSUE TITLE
No oldChangeDate and oldId in /api/changes API REST

### ISSUE THREAD

**Issue by Genkryo** [netfishers-onl/Netshot#249]
Hi,

I have a script that get last change from netshot and would like to use /configs/{id1}/vs/{id2} to get only the diff of this change.
Unfortunately, when i request /api/changes, all entry returned have no oldChangeDate and oldId data.
I have this behavior on all type of device (FW, switch, router ...)

Example
  {
    "deviceName": "xxxx",
    "deviceId": 245,
    **"oldChangeDate": null,**
    "newChangeDate": 1675530827000,
    "author": "xxxx",
    **"oldId": 0**,
    "newId": 5708
  }

In Webui, when i inspect source code of config, i can get the id of all previous config on devices.
Issue appears only when requesting via API rest.

Thank you.

**Comment by SCadilhac** [comment]
The Web UI is entirely based on the REST API so if the information is in the Web UI you should be able to retrieve it from the API the same way.
