### ISSUE TITLE
ArrayIndexOutOfBoundsException when comparing configuration with previous snapshot

### ISSUE THREAD

**Issue by x37verheij** [netfishers-onl/Netshot#254]
### ArrayIndexOutOfBoundsException when comparing configuration with previous snapshot
Hi all,
In the latest release of version 0.18.2 (and probably also in older versions), you can get an `ArrayIndexOutOfBoundsException` when you try to compare a configuration for a device with the previous snapshot. This happens when you add new lines to the bottom of a configuration file on the target device, then taking a snapshot in Netshot and lastly compare the last snapshot with the previous.

When you press the compare button and the exception occurs, the popup remains blank:
![Netshot18_2_InterfaceNowBroken](https://user-images.githubusercontent.com/15816757/222730169-5426a790-c73c-472d-9b23-c2f8c00bdbdb.png)
I expected the following (note, this is after my proposed fix):
![Netshot18_2_InterfaceExpected](https://user-images.githubusercontent.com/15816757/222730197-ca568501-19d3-452a-ae01-3725633f3f0c.png)
The netshot log collects the following exception message when the popup remains blank:
![Netshot18_2_ArrayIndexOutOfBoundsException](https://user-images.githubusercontent.com/15816757/222730648-f01523c6-487d-457e-ad93-a9dbcb9ac491.png)

The code at the time of the [0.18.2 release](https://github.com/netfishers-onl/Netshot/blob/248d2875dffd9a3f212c3ae1d7f20c4c8f559f23/src/main/java/onl/netfishers/netshot/rest/RestService.java). The exception occurs at line 1323:
![Netshot18_2_TriggeredCodeLine1323 smaller](https://user-images.githubusercontent.com/15816757/222733017-49a8e980-3ac4-474f-af1a-81afaf7f8214.png)

What happens here, is the following: `delta.getSource().getPosition()` (at line 1311) returns a value that is `>= oldLineParents.length`, resulting in an `ArrayIndexOutOfBoundsException`. My proposed fix is as simple as wrapping lines 1323 through 1327 in an if-statement that validates whether `p` is a valid index:

![Netshot18_2_TriggeredCodeLine1323NEW](https://user-images.githubusercontent.com/15816757/222738378-43163fcc-de94-46ec-9b5d-4a37469cec83.png)

#### Pull Request: https://github.com/netfishers-onl/Netshot/pull/255

**Comment by SCadilhac** [comment]
Thanks for the full details and the PR.
