### ISSUE TITLE
extract usernames from devices ( Switchs, ASA...), and stock them on file.

### ISSUE THREAD

**Issue by ychafi** [netfishers-onl/Netshot#258]
Hi Community,

we have a lots of Cisco Switch configured on Netshot, and we need to search all usernames configured on these Switchs, like " show run | include username " to extracte all usernames , and after stock this outputs on files.

Thank you for your help.

Regards,

**Comment by RGlintmeijer** [comment]
Maybe you can use the configured “netshot.snapshots.dump” directory to grep the usernames from all latest config files?

**Comment by SCadilhac** [comment]
Use a diagnostic to collect the data, and use the REST API to retrieve the results if needed elsewhere.
