### ISSUE TITLE
charset not defined

### ISSUE THREAD

**Issue by anli77** [netfishers-onl/Netshot#259]
Hi, 

When creating a custom driver for Arista EOS to support downloading an archive from the device, it seems there is an issue with the download function, the call always complains about charset not defined, and that seems to come from this: 

https://github.com/netfishers-onl/Netshot/blob/cca878e84d7a1203e056b799bde7cd80f0465e07/src/main/resources/interfaces/driver-loader.js#L535

From commit: https://github.com/netfishers-onl/Netshot/commit/cca878e84d7a1203e056b799bde7cd80f0465e07

The charset variable passed is not defined in scope of the download function, and there is no way to pass it in that I can find?

BR
/Anders.

**Comment by SCadilhac** [comment]
bc864df68d971e24768312d605b4bc138bec5840 should fix this
