### ISSUE TITLE
Driver required for Cisco Small Business SG350

### ISSUE THREAD

**Issue by opiym-7** [netfishers-onl/Netshot#266]
Hi.
Perhaps there is a ready-made driver for Cisco Small Business SG350.
Can someone share it?

**Comment by SCadilhac** [comment]
https://github.com/netfishers-onl/Netshot/blob/master/src/main/resources/drivers/Cisco_Sx.js => please give your feedback on this
Note: due to special SSH behavior on this device family, the driver might require the upcoming Netshot release (with updated SSH library).

**Comment by opiym-7** [comment]
Thanks! It works!
