### ISSUE TITLE
CheckPoint Gaia Snapshot ReferenceError: charset is not defined

### ISSUE THREAD

**Issue by uchihaitachi2** [netfishers-onl/Netshot#268]
Hi,
I tried to add a checkpoint gaia system.
The error message is: 
[INFO] Connected using SSH to 1.1.1.1:0 using credentials DEVICESPECIFIC-868ad9-20fd-4f94-9eb-5fb3a59e5.
[ERROR] Error while running snapshot using driver CheckpointGaia: 'ReferenceError: charset is not defined'.
[WARN] Unable to open an SSH socket to 1.1.1.1:0: ReferenceError: charset is not defined
[ERROR] Error while taking the snapshot: Couldn't open either SSH or Telnet socket with the device.

I can see in the logs that the driver run correclty the commands : show configuration .... add local backup ...

but it stuck on the scp step.

Could you please help?

Thanks

**Comment by uchihaitachi2** [comment]
Hi,

The error is related to the driver itself or to netshot code?

Thanks

**Comment by SCadilhac** [comment]
Looks similar to  #259

**Comment by uchihaitachi2** [comment]
Hi,
I have jut tested the last version 0.19.0 which include the fix. this time, the error message is:

ERROR] Error while running snapshot using driver CheckpointGaia: 'TypeError: invokeMember (download) on onl.netfishers.netshot.device.script.helper.JsConfigHelper failed due to: Arity error - expected: 4 actual: 5'.

[ERROR] Error while taking the snapshot: TypeError: invokeMember (download) on onl.netfishers.netshot.device.script.helper.JsConfigHelper failed due to: Arity error - expected: 4 actual: 5

Thanks for your help!

**Comment by uchihaitachi2** [comment]
Hi,
Could you please help?
Thanks

**Comment by SCadilhac** [comment]
0.19.1
