### ISSUE TITLE
Сonfiguration files on server

### ISSUE THREAD

**Issue by opiym-7** [netfishers-onl/Netshot#269]
Where are device configuration files stored locally on the server?

**Comment by momolemo** [comment]
if you want the result of snapshot there are by default only stored in database.
you can export a text version on the server filesystem following this doc : 
https://github.com/netfishers-onl/Netshot/wiki/Config-file-(netshot.conf)-reference#snapshots
the parameter netshot.snapshots.dump is what you need to look at

regards
