### ISSUE TITLE
cli.debug not working on v0.19.0

### ISSUE THREAD

**Issue by momolemo** [netfishers-onl/Netshot#270]
Hello,

I just try to update my test instance of netshot in v0.19.0 and the update process works very well and the new version have some improvment very cool :) 
variable in script and new script management are very cool nice dev !!!

I just have detect one potential bug on script function. When i try to make output some text in log during a script execution with cli.debug like i do before update, the script crash with this output.

my test script : 
```
function run(cli, device) {
	//DEBUT SCRIPT
    cli.macro("user");
    var output = cli.command("dis cu interface");
    cli.debug("coucou");
}
```
and the error output : 
```
[ERROR] Error while running script  using driver HPE SWITCH: 'TypeError: invokeMember (debug) on onl.netfishers.netshot.device.script.CliScript$1 failed due to: Unknown identifier: debug'.
```

regards

**Comment by SCadilhac** [comment]
Indeed, regression due to JRE upgrade... 6f5a7d646a489f4cf583437a6de9b2fb2cf9af4f should fix this.
