### ISSUE TITLE
FIX Generic snmp device SG350

### ISSUE THREAD

**Issue by opiym-7** [netfishers-onl/Netshot#273]
Hello.
During network scanning, the sg350 device was identified by snmp as a generic snmp device.
There is a flaw in the driver.
I fixed it and the problem was solved.
Perhaps it should be fixed for the next version?

![image](https://github.com/netfishers-onl/Netshot/assets/122613620/470cd976-01b0-43ea-b6a3-d1e72a0068c8)

**Comment by SCadilhac** [comment]
Would you like to propose a fix?

**Comment by SCadilhac** [comment]
Changed in 0444c7816c2afd74ab35b1539eab5ed171fbca39
