### ISSUE TITLE
Duplicate modules in driver CiscoIOSXR version 1.8.1

### ISSUE THREAD

**Issue by Rikharms1972** [netfishers-onl/Netshot#274]
on some ASR9K devices modules are presented double (or even more times).

See attachment for example
![duplicates](https://github.com/netfishers-onl/Netshot/assets/59537823/d9269298-3886-4390-905f-f47c9882365d)

I don`t know how to fix this in the driver, so maybe you can have a look.

Thanks.

**Comment by SCadilhac** [comment]
Do you see the duplicated items when unticking the _Show history_ checkbox?
The modules are parsed out from `admin show inventory` and `show inventory`, what do these ones look like?

**Comment by Rikharms1972** [comment]
Yes, unticking it also gives the duplicates.

Output:

show inventory | utility egrep TenGigE0/4/CPU0/9 -A 1
Mon Oct 30 10:53:09.635 CET
NAME: "module mau TenGigE0/4/CPU0/9", DESCR: "10GBASE-LR SFP+ Module for SMF"
PID: SFP-10G-LR         , VID: V02 , SN: OPM2251156L 

admin show inventory | utility egrep TenGigE0/4/CPU0/9 -A 1
Mon Oct 30 10:55:04.386 CET
NAME: "module mau TenGigE0/4/CPU0/9", DESCR: "10GBASE-LR SFP+ Module for SMF"
PID: SFP-10G-LR         , VID: V02 , SN: OPM2251156L 
![duplicates](https://github.com/netfishers-onl/Netshot/assets/59537823/41be1c6b-a985-4d02-8323-bd8c2dd6496d)

**Comment by SCadilhac** [comment]
Indeed in the current version the driver doesn't remove duplicates between `show inventory` and `admin show inventory`. To be improved.

**Comment by SCadilhac** [comment]
46019d98fd74f914cadfee8100a6f0e327a3118a should fix this.
