### ISSUE TITLE
Cisco 1000 appears as "Unknown IOS Device"

### ISSUE THREAD

**Issue by TLigniere** [netfishers-onl/Netshot#289]
Hello,
So I ended up connecting a Cisco 1000, NetShot is able to connect and interact with it without any problems but NetShot returns "Unknown IOS Device" for its family. Just wanted to point that out.
You're doing a great job, thanks for NetShot, it's truly useful.
Regards

**Comment by SCadilhac** [comment]
Hi, can you please provide an example of `show version` on the device so we can add the needed match to the driver?

**Comment by TLigniere** [comment]
Here's the sh version

Cisco IOS Software, C1000 Software (C1000-UNIVERSALK9-M), Version 15.2(7)E6, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2022 by Cisco Systems, Inc.
Compiled Tue 22-Mar-22 10:25 by mcpre

ROM: Bootstrap program is c1000 boot loader
BOOTLDR: C1000 Boot Loader (C1000-HBOOT-M) Version 15.2(7r)E3, RELEASE SOFTWARE (fc4)

CLF2-FR-SW-01 uptime is 17 weeks, 3 days, 21 hours, 17 minutes
System returned to ROM by power-on
System image file is "flash:/c1000-universalk9-mz.152-7.E6/c1000-universalk9-mz.152-7.E6.bin"
Last reload reason: power-on



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

cisco C1000-16FP-2G-L (Marvell PJ4B (584) v7 (Rev 2)) processor (revision B0) with 524288K bytes of memory.
Processor board ID X
Last reset from Reload
3 Virtual Ethernet interfaces
18 Gigabit Ethernet interfaces
The password-recovery mechanism is enabled.

512K bytes of flash-simulated non-volatile configuration memory.
Base ethernet MAC Address       : X
Motherboard assembly number     : X
Power supply part number        : X
Motherboard serial number       : X
Power supply serial number      : X
Model revision number           : B0
Motherboard revision number     : 21
Model number                    : C1000-16FP-2G-L
System serial number            : FX
Top Assembly Part Number        : X
Top Assembly Revision Number    : B0
Version ID                      : V02
CLEI Code Number                : X
Hardware Board Revision Number  : 0x02


Switch Ports Model                     SW Version            SW Image
------ ----- -----                     ----------            ----------
*    1 18    C1000-16FP-2G-L           15.2(7)E6             C1000-UNIVERSALK9-M


Configuration register is 0xF

**Comment by TLigniere** [comment]
I created a fork on https://github.com/netfishers-onl/Netshot/blob/master/src/main/resources/drivers/Cisco_IOS.js from what I understood of the file to add it

**Comment by SCadilhac** [comment]
https://github.com/netfishers-onl/Netshot/commit/a71eec5741d2380c9e0b020193600ccef107a454
