### ISSUE TITLE
NullPointerException Due to Null VendorVersion During Startup

### ISSUE THREAD

**Issue by pemo75** [netfishers-onl/Netshot#294]
Hello Netshot Team,

I am experiencing an issue when attempting to run the Netshot application on my Ubuntu system. I have installed Java 17.0.9 and have verified that it is the active Java version on my system. However, when I attempt to start the application using the command java -jar /usr/local/netshot/netshot.jar, I encounter a NullPointerException related to the vendorVersion string being null.

Here is the full error message I receive:

NETSHOT FATAL ERROR: Cannot invoke "String.matches(String)" because "vendorVersion" is null
java.lang.NullPointerException: Cannot invoke "String.matches(String)" because "vendorVersion" is null
    at onl.netfishers.netshot.Netshot.checkJvm(Netshot.java:476)
    at onl.netfishers.netshot.Netshot.main(Netshot.java:534)

I have also tried running the application with the -XX:-UsePerfData flag, as suggested in some forums, but this did not resolve the issue.

My netshot.conf configuration file is attached below for reference. I have ensured that all paths and credentials are correct and that the application has the necessary permissions to access the specified directories and files.

Could you please assist me in resolving this issue? Any guidance on what might be causing the vendorVersion to be null or how to properly configure the JVM for Netshot would be greatly appreciated.

Thank you for your time and support.

Best regards,

pemo75
[netshot.zip](https://github.com/netfishers-onl/Netshot/files/14276671/netshot.zip)

**Comment by pemo75** [comment]
Hello SCadilhac 

Thank you for your prompt response to my inquiry. I appreciate your assistance in resolving the issue I'm facing with the Netshot application on my Ubuntu system.

As I mentioned in my initial message, the Java version installed on my system is  17.0.9. Prior to this, I was using Java  8, but I encountered an error that led me to upgrade to Java  17.0.9 in an attempt to resolve the issue.

Regarding the Netshot version, I am using version v.0.19.3.

To provide you with the full log from Netshot, I will need to locate the log file. Could you please guide me on where I can find this log file? Once I have it, I will be able to share the complete log with you for further analysis.

Thank you once again for your support. I look forward to your guidance on this matter.

Best regards,

pemo75

**Comment by SCadilhac** [comment]
I suspect you are not using the right JVM that’s why I requested full `java -version`. Logs can be found in /var/log/Netshot by default.
