### ISSUE TITLE
Error using driver

### ISSUE THREAD

**Issue by opiym-7** [netfishers-onl/Netshot#295]
Hello.
I use a self-written driver for RouterOS.
The driver works correctly for all devices except one.
There are the same devices on my network with the same firmware.
It gives this error.
Tell me please what does it mean?

`[INFO] Snapshot task for device [NONAME] (172.20.20.20).
[INFO] Auto-trying SSH with credentials GW.
[INFO] Connected using SSH to 172.20.20.20.1:22 using credentials GW.
[ERROR] Error while running snapshot using driver RouterOS: 'TypeError: invokeMember (set) on onl.netfishers.netshot.device.script.helper.JsDeviceHelper failed due to: no applicable overload found (overloads: [Method[public void onl.netfishers.netshot.device.script.helper.JsDeviceHelper.set(java.lang.String,java.lang.Double)], Method[public void onl.netfishers.netshot.device.script.helper.JsDeviceHelper.set(java.lang.String,java.lang.String)], Method[public void onl.netfishers.netshot.device.script.helper.JsDeviceHelper.set(java.lang.String,java.lang.Boolean)]], arguments: [name (TruffleString), com.oracle.truffle.js.runtime.builtins.JSArrayObject@132eb6ca (JSArrayObject)])'.
[ERROR] Error while taking the snapshot: TypeError: invokeMember (set) on onl.netfishers.netshot.device.script.helper.JsDeviceHelper failed due to: no applicable overload found (overloads: [Method[public void onl.netfishers.netshot.device.script.helper.JsDeviceHelper.set(java.lang.String,java.lang.Double)], Method[public void onl.netfishers.netshot.device.script.helper.JsDeviceHelper.set(java.lang.String,java.lang.String)], Method[public void onl.netfishers.netshot.device.script.helper.JsDeviceHelper.set(java.lang.String,java.lang.Boolean)]], arguments: [name (TruffleString), com.oracle.truffle.js.runtime.builtins.JSArrayObject@132eb6ca (JSArrayObject)])`

**Comment by SCadilhac** [comment]
This means you are trying to `device.set()` an array instead of a simple type (number or string).
