### ISSUE TITLE
Software complainace is not working for Cisco ASA firewalls

### ISSUE THREAD

**Issue by anburhce** [netfishers-onl/Netshot#299]
Hi Team,

Need your help to update the ASA firewall driver , as software compliance is not working for these below mentioned ASA firewall families .

Cisco ASA 5525
Cisco ASA 5545
Cisco ASA 5585.

Kinldy do let me now if you need any more details.

**Comment by SCadilhac** [comment]
Hi, can you run the snapshot in full debug mode (https://github.com/netfishers-onl/Netshot/wiki/Snapshot-troubleshooting) and share the result so that I can update the driver?

**Comment by anburhce** [comment]
Dear Friend, 

This is the actual issue. It is not checking the software compliance. Hardware and conf backup and is working fine.

![image](https://github.com/netfishers-onl/Netshot/assets/23453745/99cbeac6-59b8-4493-a8ac-71416e3a726b)


And i  tried to run Debug snapshot but not seeing the "Enable debug log"

![image](https://github.com/netfishers-onl/Netshot/assets/23453745/dfd9992e-5dd2-44b0-8a6f-65160d4f4e56)

Am using [Netshot 0.19.3] version in my Environment.

**Comment by anburhce** [comment]
Family and version details are here 
![image](https://github.com/netfishers-onl/Netshot/assets/23453745/1f7eaa79-4254-4097-8a16-e776885bba25)

part number details are here 

![image](https://github.com/netfishers-onl/Netshot/assets/23453745/9f8891df-70df-4fae-813e-226682480be1)

Software compliance  added details 

![image](https://github.com/netfishers-onl/Netshot/assets/23453745/e9351c0c-7371-46ad-ab5a-a01d6904e184)

![image](https://github.com/netfishers-onl/Netshot/assets/23453745/b6b6b46b-2c08-45fc-be08-bffa3822064a)

And finally when i run it getting this error.

![image](https://github.com/netfishers-onl/Netshot/assets/23453745/bb618a6c-afc1-4dbc-a588-dc8fbb7857e3)

under reports  tab i see all the devices are non-complaint 

![image](https://github.com/netfishers-onl/Netshot/assets/23453745/3a0175e6-8bf7-4be0-9cf0-c2dac0f5e126)

**Comment by SCadilhac** [comment]
Weird. I would suspect a hidden space or something similar...
You may want to clear the _Device Family_ and _Part Number_ fields in the compliance rule and try again. If not better, can you double check (API) that the version doesn't contain any space or other unexpected character?

**Comment by anburhce** [comment]
It is failing because of version only. if i remove version on the compliance tab 

![image](https://github.com/netfishers-onl/Netshot/assets/23453745/c4b6f7b6-181f-42bc-8d1e-03f09dc24c10)
![image](https://github.com/netfishers-onl/Netshot/assets/23453745/3995be81-45eb-4395-9ee7-c11ccace9eb8)


I tried it with and without space , but still no luck. 

How do we solve this issue ?

**Comment by SCadilhac** [comment]
Can you use the API to check the detected version of the device?
Go to _Help_ > _API browser_. 
Find `GET /devices/{id}`, expand the section, click `Try it out`, give the device ID, and click `Execute`. Check `softwareVersion` entry in the resulting JSON.

**Comment by anburhce** [comment]
Hi Friend,


![image](https://github.com/netfishers-onl/Netshot/assets/23453745/6e6f38d9-7cb5-419f-810c-7dab03da6161)

[netshot - PA.txt](https://github.com/netfishers-onl/Netshot/files/15162264/netshot.-.PA.txt)

**Comment by anburhce** [comment]
Hi Scadilhac,

Kindly help.

**Comment by SCadilhac** [comment]
You are sharing an example from the API doc, not the query result as requested.
You should have real values in the result, not values like `"string"`.

**Comment by anburhce** [comment]
Hi  Scadilhac,

Kindly check now .

![image](https://github.com/netfishers-onl/Netshot/assets/23453745/f30066ce-d08f-41a3-be70-a20ef690b7e2)

**Comment by SCadilhac** [comment]
OK, so there is a space character at the end of the software version.
I've updated the driver file, you can update (or you can the space to your rule, to check).

**Comment by anburhce** [comment]
Hi  Scadilhac,

Can you provide the stpes to update only the driver? 
Also share me the driver filename which you have updated.
