### ISSUE TITLE
NXOS driver does not allow colored prompt

### ISSUE THREAD

**Issue by AlainMoretti** [netfishers-onl/Netshot#3]
NXOS driver does not work when colored prompt is used because the prompt regex does not match special characters. 

Maybe line 128 of [Cisco_NX-OS.js](https://github.com/netfishers-onl/Netshot/blob/master/src/main/resources/drivers/Cisco_NX-OS.js) should be : 
		prompt: /([A-Za-z\-_0-9\.]+#) /,
instead of : 
		prompt: /^([A-Za-z\-_0-9\.]+#) $/,

Regex max match rule should keep whole hostname inside brackets.

**Comment by SCadilhac** [comment]
Thanks for the comment.
