### ISSUE TITLE
version and copyright dates are missing/wrong

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#304]
![image](https://github.com/netfishers-onl/Netshot/assets/7047326/6041b6ec-a9e1-4ed3-98b3-796c86af28dc)

am running on the latest 0.19.3

**Comment by SCadilhac** [comment]
Thanks, will fix this

**Comment by pizu** [comment]
![image](https://github.com/netfishers-onl/Netshot/assets/7047326/fe1011b0-7ffb-4a91-83ce-f698dbd481c8)
VERSION.txt seems to be missing
![image](https://github.com/netfishers-onl/Netshot/assets/7047326/7316e72b-f52b-4e60-9bad-64e57e0b6188)


copyright date seems to be fixed in the last version.

Thanks :-)
