### ISSUE TITLE
gu install python issue

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#307]
# ./bin/gu install python -v
Downloading: Artifacts catalog (source: https://gds.oracle.com/api/20220101/artifacts/?metadata=java%3Ajdk17&metadata=arch%3Aamd64&metadata=os%3Alinux&productId=D53FAE8052773FFAE0530F15000AA6C6&limit=1000)
Receiving 19 kB: Done.
Trying to login to channel generic_linux_x86_64_graalvm_jdk17, at https://linux-update.oracle.com/rpc/api
Skipping ULN EE channels, no username provided.
Downloading: Component catalog (source: https://www.graalvm.org/component-catalog/v2/graal-updater-ee-component-catalog-java17.properties)
Receiving 62 kB: Done.
Error: Component "python" is not available in catalog.

# ./bin/gu list
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
graalvm                  23.0.3              GraalVM Core                  Supported                     
icu4j                    23.0.3              ICU4J                         Supported                     gds.oracle.com
js                       23.0.3              Graal.js                      Supported                     gds.oracle.com
llvm-toolchain           23.0.3              LLVM.org toolchain            Supported                     gds.oracle.com
native-image             23.0.3              Native Image                  Early adopter                 
regex                    23.0.3              TRegex                        Supported                     gds.oracle.com
[root@nettools02 graalvm]# ./bin/gu available
Downloading: Artifacts catalog from gds.oracle.com
Skipping ULN EE channels, no username provided.
Downloading: Component catalog from www.graalvm.org
ComponentId              Version             Component name                Stability                     Origin 
---------------------------------------------------------------------------------------------------------------------------------
espresso                 23.0.3              Java on Truffle               Supported                     gds.oracle.com
espresso-llvm            23.0.3              Java on Truffle LLVM Java librSupported                     gds.oracle.com
icu4j                    23.0.3              ICU4J                         Supported                     gds.oracle.com
jipher                   23.0.3              Jipher JCE Provider           Supported                     gds.oracle.com
js                       23.0.3              Graal.js                      Supported                     gds.oracle.com
llvm                     23.0.3              LLVM Runtime Core             Supported                     gds.oracle.com
llvm-toolchain           23.0.3              LLVM.org toolchain            Supported                     gds.oracle.com
nodejs                   23.0.3              Graal.nodejs                  Supported                     gds.oracle.com
regex                    23.0.3              TRegex                        Supported                     gds.oracle.com
visualvm                 23.0.3              VisualVM                      Supported                     gds.oracle.com

#java -version
java version "17.0.10" 2024-01-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 17.0.10+11.1 (build 17.0.10+11-LTS-jvmci-23.0-b27)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.10+11.1 (build 17.0.10+11-LTS-jvmci-23.0-b27, mixed mode, sharing)

**Comment by pizu** [comment]
![image](https://github.com/netfishers-onl/Netshot/assets/7047326/e3c20306-a5a4-4ccb-9c69-a59a5153ebaf)
![image](https://github.com/netfishers-onl/Netshot/assets/7047326/5c598513-d27f-4e53-9e40-a5e4293577c9)
![image](https://github.com/netfishers-onl/Netshot/assets/7047326/20d6a577-6078-4ac7-9fc3-7a0156febd7d)

**Comment by SCadilhac** [comment]
The install guide suggests to install 17.0.8-graal while you are trying 17.0.10, which cannot be installed the same way.
