### ISSUE TITLE
SNMP Change detection

### ISSUE THREAD

**Issue by ebinet81** [netfishers-onl/Netshot#311]
Hello,
We installed the last version of Netshot (0.19.4) but the change detection with SNMP did not work. Our Netshot version is installed on Ubuntu 24.04. 
When we checked how Netshot was listening, we notices that 127.0.1.1:1162.
We downgraded Netshot and change detection is working since we are in 0.19.2 and Netshot is listening on *:1162.

**Comment by SCadilhac** [comment]
Fixed in 662d0b38888c0b591408dcf0721be0b1c70de235
