### ISSUE TITLE
Errror 500 on /api/user using API Token

### ISSUE THREAD

**Issue by M0NsTeRRR** [netfishers-onl/Netshot#317]
Token is created with full admin access
![image](https://github.com/user-attachments/assets/ede1f093-faee-48fb-be73-216bce442cdb)

Using Swagger with an authenticated user
```
curl -X 'GET' \
  'https://netshot.example.com/api/user' \
  -H 'accept: application/json'
```
return
```
{
  "id": 0,
  "local": false,
  "username": "ludovic.ortega",
  "level": 1000
}
```

Using swagger with ApiTokenAuth
```
curl -X 'GET' \
  'https://netshot.example.com/api/user' \
  -H 'accept: application/json' \
  -H 'X-Netshot-API-Token: xxxxxxxx'
```
return HTTP error 500

**Comment by SCadilhac** [comment]
Fixed by 84fc64c613471f1c0f5c9691722b343f6f321da3
Thanks for reporting!
