### ISSUE TITLE
Running a script and get : "No regexp prompt in the selected mode."

### ISSUE THREAD

**Issue by PierreCoudercy** [netfishers-onl/Netshot#318]
Hello,

I am currently trying to run a command with the script function of Netshot I am trying to execute a "show ip interface brief"
But the command keep failling with the error "No regexp prompt in the selected mode."
The default script is working properly.
To run the command I am using the cli.command keyword.

Can someone enlight me on what is going on ?

**Comment by SCadilhac** [comment]
Can you please share the full script? Does it happen with Cisco IOS driver?
