### ISSUE TITLE
Failed task does not shows - error 500

### ISSUE THREAD

**Issue by M0NsTeRRR** [netfishers-onl/Netshot#319]
When using the UI and clicking on 'Failed tasks,' nothing appears. When I check the console, I see a 500 error.
![image](https://github.com/user-attachments/assets/df390b47-82d3-4461-ae53-8e2f048fbf23)

API call : https://netshot.example.fr/api/tasks?status=FAILURE&before=1730156399999&after=1730070000000

**Comment by shootheart** [comment]
get the same issue, also on "All tasks".

**Comment by SCadilhac** [comment]
Fix in eb877baa68c22c808b6a8b94d7ce2159ae830428
Thanks for reporting
