### ISSUE TITLE
SNMPv3

### ISSUE THREAD

**Issue by rajece1989** [netfishers-onl/Netshot#32]
HI Team ,

In our organization, we are using SNMPv3 for All device.

can we know when SNMPv3 can be enabled and date of release for the same.

**Comment by SCadilhac** [comment]
This is expected for end of next week.

**Comment by SCadilhac** [comment]
See version 0.11.0 published last week.

**Comment by rajece1989** [comment]
Still I can see only 0.8.0 version only in website

Can you help you agree the line to download ..

**Comment by SCadilhac** [comment]
You can find the latest releases on the GitHub page itself:
https://github.com/netfishers-onl/Netshot/releases
