### ISSUE TITLE
Port 8443

### ISSUE THREAD

**Issue by orgitnized** [netfishers-onl/Netshot#325]
In the directions, it states to use port 8443 after the install is complete, here: https://github.com/netfishers-onl/Netshot/wiki/Installing-Netshot-0.16-or-more-recent-on-Linux-server

Is this correct? Mine does not listen on that port, and instead uses 443. I don't see anywhere in the directions stating to modify a port to make it use port 8443. Just adding this for clarification in the directions so people don't finish an install and wonder why they can't connect to the instance.

**Comment by SCadilhac** [comment]
How does your netshot.conf file look like?

```
netshot.http.baseport = 8443
```

**Comment by orgitnized** [comment]
Vanilla install of your app shows this

```
# REST
netshot.http.ssl.enabled = true
netshot.http.ssl.keystore.file = /usr/local/netshot/netshot.pfx
netshot.http.ssl.keystore.pass = password
#netshot.http.baseurl = https://localhost
netshot.http.baseurl = https://0.0.0.0
#netshot.http.baseport = 8443
inetshot.http.trustxforwardedfor = false
```

**Comment by SCadilhac** [comment]
Adding `:8443` to `baseurl` or uncommenting `baseport` should make it.
I've updated the default dist config to be consistent with docs.
