### ISSUE TITLE
Driver for FortiOS

### ISSUE THREAD

**Issue by marcamouzoun** [netfishers-onl/Netshot#326]
Hello,

when post-warning is disabled on fortigate, config backup works. 

but when enabled, there is an error when trying to capture the config. 

I tried unsuccessfully to update fortinetFortiOS drivers.

See attached debug file. 
[debug_349.log](https://github.com/user-attachments/files/17996638/debug_349.log)

**Comment by SCadilhac** [comment]
Thanks for reporting. I just added the support for post-login banner to FortiOS driver version 5.8.
Commit 66c7c251289805559387987fb35847d7a7af9703
Let me know if any problem.

**Comment by marcamouzoun** [comment]
It worked like a charm. Thank you.
