### ISSUE TITLE
SSH another port 

### ISSUE THREAD

**Issue by myroma** [netfishers-onl/Netshot#33]
I ask you to consider the possibility of adding the function of changing the port of the SSH in credential settings

**Comment by SCadilhac** [comment]
This is already possible at the device level (using the `Override connection settings` option).
Can you explain why you would need it at the credential level?

**Comment by myroma** [comment]
Some devices in my network use alternate port number for SSH.

**Comment by SCadilhac** [comment]
So you can just use the feature I mentioned above.

**Comment by myroma** [comment]
In Override connection settings I can not enter port number, there is no such field

**Comment by myroma** [comment]
Sorry, It was bug in my browser

**Comment by myroma** [comment]
Thank you SCadilhac
