### ISSUE TITLE
Netshot 12.2 SNMPv3

### ISSUE THREAD

**Issue by myroma** [netfishers-onl/Netshot#37]
Still the username field in SNMPv3 did not appear

**Comment by myroma** [comment]
as seen in the screenshot
![untitled](https://user-images.githubusercontent.com/47498706/53384912-c2f98e80-39a6-11e9-86db-809f11cebcea.jpg)

**Comment by myroma** [comment]
Also after updating,
Compliance tab became emtpy!

**Comment by SCadilhac** [comment]
Have you forcebly refreshed your browser?

**Comment by myroma** [comment]
Yes, I use latest version of browser. (60.5.2esr (32-bit))

**Comment by SCadilhac** [comment]
I mean use Ctrl + F5 (Windows/Linux) to force a refresh of the page.

**Comment by myroma** [comment]
yes of course

**Comment by SCadilhac** [comment]
Weird then. I can't see this issue.
![image](https://user-images.githubusercontent.com/14115661/53495525-68445d80-3aa0-11e9-97d4-7246ca8defae.png)
Can you double-check the right version is displayed in the About dialog?
Then you can open the Developer Tools in Firefox, switch to Debug tab, open js > views > admin > EditCredentialSetDialog.js file, and extract the content.

**Comment by myroma** [comment]
Netshot 12.3 has resolved this issue, great!

**Comment by SCadilhac** [comment]
There is no related change in 0.12.3, so you probably were not properly running 0.12.2.
