### ISSUE TITLE
Changes over the last days

### ISSUE THREAD

**Issue by myroma** [netfishers-onl/Netshot#38]
Netshot don't show graphs of changes!
![untitled](https://user-images.githubusercontent.com/47498706/53538838-785c4b80-3b39-11e9-893d-196567e5cc56.jpg)

**Comment by SCadilhac** [comment]
Not seeing this issue, you have to give more details. Please also in such case open the developper tools and look at any error message there.

**Comment by myroma** [comment]
window.controllers/Controllers is deprecated. Do not use it for UA detection.  ace.js:1:18298
unreachable code after return statement  ConfigComplianceReportView.js:188:1
Use of nsIFile in content process is deprecated. NetUtil.jsm:302:12
Use of nsIFile in content process is deprecated.  filesystem.js:40:9
Successfully compiled asm.js code (total compilation time 74ms; unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script'))  demangle.js
window.controllers/Controllers is deprecated. Do not use it for UA detection.  ace.js:1:18298
unreachable code after return statement  ConfigComplianceReportView.js:188:1
window.controllers/Controllers is deprecated. Do not use it for UA detection.  ace.js:1:18298
unreachable code after return statement  ConfigComplianceReportView.js:188:1
unreachable code after return statement  DataExportReportParamsModel.js:44:3

**Comment by SCadilhac** [comment]
Should be now fixed in 0.12.5.
