### ISSUE TITLE
Compliance Setup

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#40]
Hi,

Am trying to setup the compliance check for cisco ios and nx-os and am having issues..

Example Config below:
![image](https://user-images.githubusercontent.com/7047326/54823361-e236c380-4ca7-11e9-98a7-0c521919e4f5.png)

this is not working.. what am I doing wrong?

**Comment by SCadilhac** [comment]
As you are not giving a context, and _Match whole section_ is checked, Netshot checks whether the two lines you provided match the entire configuration, which is not the case.
You should uncheck _Match whole section_.

**Comment by pizu** [comment]
Still not working :(

**Comment by SCadilhac** [comment]
Please provide the full example configuration and a new snapshot of the rule.

**Comment by pizu** [comment]
Hi,

Thanks for your reply,

Am trying the below:
![image](https://user-images.githubusercontent.com/7047326/57233162-678af300-701e-11e9-8b6e-a111ae07ab40.png)

I'd like to check if any of those lines all or at lease 1 of them is in the configuration.

**Comment by SCadilhac** [comment]
If you put all the lines like that, Netshot will look for all the lines, precisely as they are given. If you want to check if at least one is present, you must check _Regular expression_ and use something like:
`^ntp server 172\.16\.(181\.34|200\.11|200\.12|200\.13)$`.
