### ISSUE TITLE
Help with extracting data.

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#41]
Hi,

am going to create a script to read the data from the database and I cannot find the report tables.

I need to extract it and populate the data on an excel.

Thanks.

**Comment by SCadilhac** [comment]
There is no specific table for the reports currently, data is extracted and aggregated from the other tables.
You might want to use the REST API rather than query the DB directly.

**Comment by pizu** [comment]
Do you have any documentation on the RESR API?

**Comment by SCadilhac** [comment]
A quick start: https://github.com/netfishers-onl/Netshot/wiki/Using-the-REST-API
