### ISSUE TITLE
How do I upgrade to 0.12.6?

### ISSUE THREAD

**Issue by orgitnized** [netfishers-onl/Netshot#43]
I see the wiki here: https://github.com/netfishers-onl/Netshot/wiki/Updating-Netshot-to-a-new-version
But it shows that you're downloading netshot.jar from somewhere.  Where do I get this file?  When I look at 0.12.6-related items, it references netshot.java and not netshot.jar.
Can someone help me please?  I'm on 0.8.1 looking to go to 0.12.6 - thanks!

**Comment by SCadilhac** [comment]
Good point, I've added some details to the Wiki page.
FYI, the release page (with up-to-date packages to download) is there: https://github.com/netfishers-onl/Netshot/releases
