### ISSUE TITLE
Rancid To Netshot

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#51]
Hi,

We need to transfer over 100 new devices from rancid but we would like to keep all the the configurations and transfer them too. also is there any option to export the devices too.

Thanks.

**Comment by SCadilhac** [comment]
You probably have to manually import the data into the database.
To export the devices, go to _Reports_ > _Data export_.

**Comment by pizu** [comment]
Hi,

Import not export.. sorry.

Thanks.
