### ISSUE TITLE
trouble with gaia device

### ISSUE THREAD

**Issue by myroma** [netfishers-onl/Netshot#57]
I do not add Gaia device in Netshot.

[INFO] Snapshot task for device [NONAME] (xxx.xxx.xxx.xxx).
[ERROR] Error while taking the snapshot: java.lang.NullPointerException in at line number 341 at column number 3
[ERROR] Error while downloading file for attribute key backupArchive: null
[ERROR] Error while running snapshot using driver CheckpointGaia: 'java.lang.NullPointerException in at line number 341 at column number 3'.

**Comment by SCadilhac** [comment]
An additional check is needed there to make this error more explicit. Will look at it.
Have you properly set the following variable in _netshot.conf_?
```
# Where to store the binary snapshot files
netshot.snapshots.binary.path = /var/local/netshot
```

**Comment by myroma** [comment]
I have added the variable but nothing change.
I still can not add a Gaia device!

**Comment by SCadilhac** [comment]
Can you please provide the related logs, cf. `/var/log/netshot/netshot.log`?
