### ISSUE TITLE
Device Credentials 

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#58]
Im not able to delete Device Credentials, it is giving me this error : 

Error: Unable to delete the credential set, there must be devices or tasks using it.

I have run a task once and deleted the device after, there is no schedule or no place i can delete a task ?
any1 have encounter this kind of problem ? maybe im missing knowledge of how to remove a clear a old task ? i tried to purge but i cant purge anything before 15 days ?

**Comment by SCadilhac** [comment]
Which version are you running?

**Comment by PatrickDenis** [comment]
Im using 14.0, thank you in advance ( pour cette reponse vraiment rapide :) ( juste comme ca tu savais que le site web ne fonctionne plus ? )

**Comment by SCadilhac** [comment]
Thanks (for the website).
I will try to reproduce the error you had and get back to you.

**Comment by SCadilhac** [comment]
Which DB do you use? MySQL or PostgreSQL?
Can you please provide the content or `/var/log/netshot/netshot.log` whenever you get the error?
