### ISSUE TITLE
F5 Support in Netshot

### ISSUE THREAD

**Issue by sajaltiwari** [netfishers-onl/Netshot#6]
Hello,
Can we get support for F5 device and also copy ucs file from it?

**Comment by SCadilhac** [comment]
Hello,

We have no official driver for F5 devices at the moment. No time for it at the moment unless there is a strong demand. Any contribution is welcome. :-)

**Comment by pizu** [comment]
+1 :)

**Comment by smahamin** [comment]
I've written this basic script for F5. I'm getting errors when I'm uploading the driver in NetShot device. I'm attaching the script. Can someone please suggest changes to be made ?
[F5.zip](https://github.com/netfishers-onl/Netshot/files/1723233/F5.zip)

**Comment by smahamin** [comment]
I've written a script for F5 driver. I'm getting errors when I'm uploading that driver file into NetShot application. I'm attaching the script. Can someone suggest any changes to be made?
[F5.zip](https://github.com/netfishers-onl/Netshot/files/1723389/F5.zip)

**Comment by SCadilhac** [comment]
Hi @smahamin,
The item names in the Config object must start with a lower case letter: rename 'F5Version' to 'f5Version'. Calling this BigIp rather than F5 would probably make sense by the way :-)
