### ISSUE TITLE
Save Issue with dynamic devicegroups and expressions using diagnostic

### ISSUE THREAD

**Issue by svdleer** [netfishers-onl/Netshot#67]
Hi,

We have an diagnostic configured for an Cisco Device.
We use the result of the diagnostic to create a dynamic devicegroup.

When we enter the expression into the dynamic devicegroup for the 1st time, the expression and devicegroup are saved without any issue.

The expression that is created (and can be saved the 1st time without issue) is : 
[Diagnostic "ASR-920-LICENSE-CHECK"] IS "REGISTERED"

But when we want to edit the dynamic devicegroup again (without altering the expression which is already loaded in the dynamic devicegroup when we open it again) the dynamic devicegroup cannot be saved again.

Error message there is : 
Error: Invalid query for the group definition.

We noticed that the expression which is now in the edit field has changed from : 
[Diagnostic "ASR-920-LICENSE-CHECK"] IS "REGISTERED"
to 
[DIAGNOSTIC (ASR-920-LICENSE-CHECK)] IS "REGISTERED"

When we change the text in the edit field back to : 
[Diagnostic "ASR-920-LICENSE-CHECK"] IS "REGISTERED" 

We can save the dynamic group again.

Attached pictures:
1) Diagnostic rule
2) Dynamic devicegroup 1st time (saving ok)
3) Dynamic devicegroup after opening and attempt to save again

Hope you can help us to resolve this issue.

Cheers!
Silvester
![dynamicgroupnok](https://user-images.githubusercontent.com/60779915/81707456-f66fee00-9470-11ea-80c0-4f5974c2d7aa.jpg)
![dynamicgroupok](https://user-images.githubusercontent.com/60779915/81707461-f7a11b00-9470-11ea-8c34-cbc7135d62a4.jpg)
![diagnostic](https://user-images.githubusercontent.com/60779915/81707464-f7a11b00-9470-11ea-9f88-adf94b2b9e78.jpg)

**Comment by SCadilhac** [comment]
Thanks the report, should be fixed now, will be integrated in the next release.

**Comment by svdleer** [comment]
Confirmed fixed
