### ISSUE TITLE
Syslog Server Not Triggering a Snapshot

### ISSUE THREAD

**Issue by nperez91** [netfishers-onl/Netshot#68]
Set up a switch to use port 1514 for syslog to the device and verifed traffic is reaching through firewall and performed a tcpdump and see the device listening on udp 1514 but nothing is triggered when I change something on that switch.  I dont see the snapshot happening.  Device is added in, can pull SNMP, can do pull a snapshot manually when I hit the snapshot button but doesnt do this automatically when a change is sent.

**Comment by nperez91** [comment]
Device that I am testing on is a Cisco 3560X.

**Comment by nperez91** [comment]
Also checked /var/log/netshot/netshot.log and audit.log and do not see anything populating in regards to syslog.  I am running the latest version of Ubuntu using PostGreSQL (MySQL) <-- wouldnt function (command set to new and it doesnt support the newest command set).

**Comment by SCadilhac** [comment]
You can try to enable more debugging, e.g. by adding `netshot.log.class.onl.netfishers.netshot.collector.SyslogServer = ALL` to netshot.conf (and restarting the service).
Have you checked your iptables rules?
