### ISSUE TITLE
Compliance

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#75]
Hi, 

Thank you again for that piece of art Netshot.

This is a request for an example visually of how to configure a compliance for Hardware and Software.
Configuration compliance i was able to figure it out :) and it works like a Charm. 

On another point. we are using the Cisco 9400 and 9500 family  and im getting this message in the family field in general :

Family                     Unknown IOS device

Thank you in advance.

**Comment by SCadilhac** [comment]
Hello,

Can you provide `show version` output taken on those Catalyst 9400 and 9500 switches?

Thanks,
Sylvain

**Comment by PatrickDenis** [comment]
Cisco IOS XE Software, Version 16.09.05
Cisco IOS Software [Fuji], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 16.9.5, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2020 by Cisco Systems, Inc.
Compiled Thu 30-Jan-20 18:53 by mcpre


Cisco IOS-XE software, Copyright (c) 2005-2020 by cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
licensed under the GNU General Public License ("GPL") Version 2.0.  The
software code licensed under GPL Version 2.0 is free software that comes
with ABSOLUTELY NO WARRANTY.  You can redistribute and/or modify such
GPL code under the terms of GPL Version 2.0.  For more details, see the
documentation or "License Notice" file accompanying the IOS-XE software,
or the applicable URL provided on the flyer accompanying the IOS-XE
software.


ROM: IOS-XE ROMMON
BOOTLDR: System Bootstrap, Version 16.6.2r[FC1], RELEASE SOFTWARE (P)

SBFR602AiL2 uptime is 10 weeks, 2 days, 10 hours, 15 minutes
Uptime for this control processor is 9 weeks, 3 days, 21 hours, 40 minutes
System returned to ROM by SSO Switchover at 23:08:12 EDT Fri May 29 2020
System image file is "bootflash:packages.conf"
Last reload reason: LocalSoft



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.


Technology Package License Information: 

------------------------------------------------------------------------------
Technology-package                                     Technology-package
Current                        Type                       Next reboot  
------------------------------------------------------------------------------
network-essentials      Smart License                    network-essentials  
dna-essentials          Subscription Smart License       dna-essentials                


Smart Licensing Status: UNREGISTERED/EVAL MODE

cisco C9407R (X86) processor (revision V01) with 1943258K/6147K bytes of memory.
Processor board ID FXS2341Q2FS
3 Virtual Ethernet interfaces
192 Gigabit Ethernet interfaces
40 Ten Gigabit Ethernet interfaces
4 Forty Gigabit Ethernet interfaces
32768K bytes of non-volatile configuration memory.
15956836K bytes of physical memory.
10444800K bytes of Bootflash at bootflash:.
1638400K bytes of Crash Files at crashinfo:.
0K bytes of WebUI ODM Files at webui:.
10444800K bytes of Bootflash at bootflash-1-0:.
1638400K bytes of Crash Files at crashinfo-1-0:.

Base Ethernet MAC Address          : 34-ED-1B-E1-68-C0
Motherboard Assembly Number        : 4A39
Motherboard Serial Number          : FXS233600S7
Model Revision Number              : V02
Motherboard Revision Number        : 1
Model Number                       : C9407R              
System Serial Number               : FXS2341Q2FS

Configuration register is 0x102

**Comment by PatrickDenis** [comment]
im using C9410R C9407R

**Comment by PatrickDenis** [comment]
Thank you ! Everything is now working :)
