### ISSUE TITLE
Question / Request

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#76]
Hi ,

Is it possible to create nested group ?  

exemple :

- Fleet
    - Ship1
        -L3
        -L2
    - Ship2

Thank you in advance.

**Comment by SCadilhac** [comment]
No, groups cannot be nested, however you can organize them within a tree of folders, e.g. create "L3" group within folder "Fleet/Ship1".

**Comment by PatrickDenis** [comment]
Thank you, does it mean by applying something to fleet everything under that folder will be recursive ?

Thks again :)


Sent from my iPhone

On Aug 13, 2020, at 4:42 PM, SCadilhac <notifications@github.com> wrote:

﻿

No, groups cannot be nested, however you can organize them within a tree of folders, e.g. create "L3" group within folder "Fleet/Ship1".
