### ISSUE TITLE
Device Family  problem 

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#78]
Hi,

i encounter a small problem , The Cisco 3500-XL family over rules the 3560 : and the regex need to be updated too : 

`.*WS-[CX]35[0124].*`

Thank you :)

**Comment by SCadilhac** [comment]
Could propose a PR?

**Comment by PatrickDenis** [comment]
> Could you propose a PR?

ok will try never did that :)

**Comment by SCadilhac** [comment]
Thanks - simpler fix eventually (and need to increment driver's version for clarity)
