### ISSUE TITLE
Groups Folders

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#79]
By trying to do some nested folder , it created 3 folders with the same name somehow ?
how can i delete the folders ? if there's nothing showing in them ?

![image](https://user-images.githubusercontent.com/56882992/91350557-da405480-e7b4-11ea-9d15-614b293f3a51.png)

Thank you in advance,

**Comment by SCadilhac** [comment]
Looks like a bug when using `\` instead of `/`.

**Comment by PatrickDenis** [comment]
> Looks like a bug when using `\` instead of `/` as folder separator.
yes , just realize that , when looking at your advice 13 days ago. my bad !

can i go delete them from the code ?

**Comment by SCadilhac** [comment]
The next release should fix this. For now you can still make the change directly into the DB, or use the API.

**Comment by PatrickDenis** [comment]
Perfect Thank you !
