### ISSUE TITLE
Advance Search

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#86]
Hi, was just wondering if it possible to use regex in the advance search string ?

**Comment by SCadilhac** [comment]
Not in the current version

**Comment by SCadilhac** [comment]
d62cb393c040991c8718bc5b2d1d1a9d536d039f implements RegExp-based queries

**Comment by PatrickDenis** [comment]
Just saw that you implemented it :) 

Thank you !
