### ISSUE TITLE
Support for Port Forwarded Devices?

### ISSUE THREAD

**Issue by Kriztofen** [netfishers-onl/Netshot#89]
Hi all,

I've been testing this application and so far I think it's brilliant!

I've added a few test devices to it and it's working really well so far, however when I attempted to add two devices that were port-forwarded it didn't seem to like it.

As an example:

192.168.0.10:4444
192.168.0.10:5555

![image](https://user-images.githubusercontent.com/32734784/104425897-1e23d280-5579-11eb-98ad-f1cc073abd24.png)

I was just wondering if it is possible and if I'm missing how to add them?

If not that's OK it's not a massive issue. :)

**Comment by SCadilhac** [comment]
You should still enter the real IP address of the device in _IP Address_ field, but tick the _Override connection settings_ box and enter there your proxy or port forwarding settings.

**Comment by Kriztofen** [comment]
> You should still enter the real IP address of the device in _IP Address_ field, but tick the _Override connection settings_ box and enter there your proxy or port forwarding settings.

That's awesome, thank you for the response :)
