### ISSUE TITLE
Driver Cisco ASA Does not support ASA with multiple context

### ISSUE THREAD

**Issue by uchiha-dev** [netfishers-onl/Netshot#90]
Hello,

Does the Cisco ASA driver support Firewall with multicontext?
 
I am trying to backup  ASA FW with multicontext but it does not work.

Messsage error: 

[INFO] Snapshot task for device [NONAME] (x.x.x.x).
[INFO] Connected using SSH to x.x.x.x:0 using credentials DEVICESPECIFIC-ad0f8a39-3634-443a-9f07-0028dc2940cc.
[ERROR] Error while taking the snapshot: org.hibernate.exception.DataException: could not execute statement
[INFO] Connected using SSH to  x.x.x.x:0 using credentials DEVICESPECIFIC-ad0f8a39-3634-443a-9f07-0028dc2940cc.

Thanks for your support

Best Regards,

**Comment by SCadilhac** [comment]
Multicontext is not supported on the current version.
But there seems to be another issue here (cf. DataException).
Can you please share Netshot log, `/var/log/netshot/netshot.log`?
