### ISSUE TITLE
Modules Informations not retrieved from Cisco ASA

### ISSUE THREAD

**Issue by uchiha-dev** [netfishers-onl/Netshot#91]
Hi,

It seems that Cisco ASA driver does not retrieve Modules Information (Slot, Part Number and Serial Number).

The Firewall does support show inventory.

Bellow the output of show inventory:

Name: "Chassis", DESCR: "ASA 5515-X with SW, 6 GE Data, 1 GE Mgmt, AC"
PID: ASA5515           , VID: V03     , SN: FGL1XXXMZ

Name: "Storage Device 1", DESCR: "Model Number: Micron_M550_MTFK128MAY"
PID: N/A               , VID: N/A     , SN: MXA19XXXXHN

Netshot version: 0.15.2
Please Help!

Thanks

**Comment by SCadilhac** [comment]
Can you please share a full trace of the snapshot in order to improve the driver?
https://github.com/netfishers-onl/Netshot/wiki/Snapshot-troubleshooting
assuming there is no sensitive information there.

**Comment by uchiha-dev** [comment]
I don't have the last option when I click on Tacke snapshot:

![image](https://user-images.githubusercontent.com/77418645/104661413-c4322280-56c8-11eb-9170-e7446bc81bab.png)

**Comment by SCadilhac** [comment]
As explained in the guide, you have to double-click the icon to get the hidden option.

**Comment by uchihaitachi2** [comment]
Hi,

Sorry for the delay.

Bellow output:



^(FIREWALL\-IN\-3ABC# )$

2021-06-07T13:23:33.401Z About to send the following command:

show inventory

Hexadecimal:

73 68 6f 77 20 69 6e 76 65 6e 74 6f 72 79 0d

Expecting one of the following 2 pattern(s) within 120000ms:

^(FIREWALL\-IN\-3ABC# )$

^<--- More --->$

2021-06-07T13:23:33.405Z Received the following output:

show inventory

Name: "Chassis", DESCR: "ASA 5540 Adaptive Security Appliance"

PID: ASA5540           , VID: V05     , SN: JMX1420L0BB

 

Name: "power supply", DESCR: "ASA/IPS 180W AC Power Supply"

PID: ASA-180W-PWR-AC   , VID: V02 , SN: DTN140599CH

 

 

FIREWALL-IN-3ABC#

Hexadecimal:

73 68 6f 77 20 69 6e 76 65 6e 74 6f 72 79 0d 0a 4e 61 6d 65 3a 20 22 43 68 61 73 73 69 73 22 2c

20 44 45 53 43 52 3a 20 22 41 53 41 20 35 35 34 30 20 41 64 61 70 74 69 76 65 20 53 65 63 75 72

69 74 79 20 41 70 70 6c 69 61 6e 63 65 22 0d 0a 50 49 44 3a 20 41 53 41 35 35 34 30 20 20 20 20

20 20 20 20 20 20 20 2c 20 56 49 44 3a 20 56 30 35 20 20 20 20 20 2c 20 53 4e 3a 20 4a 4d 58 31

34 32 30 4c 30 44 4d 0d 0a 0d 0a 4e 61 6d 65 3a 20 22 70 6f 77 65 72 20 73 75 70 70 6c 79 22 2c

20 44 45 53 43 52 3a 20 22 41 53 41 2f 49 50 53 20 31 38 30 57 20 41 43 20 50 6f 77 65 72 20 53

75 70 70 6c 79 22 0d 0a 50 49 44 3a 20 41 53 41 2d 31 38 30 57 2d 50 57 52 2d 41 43 20 20 20 2c

20 56 49 44 3a 20 56 30 32 20 2c 20 53 4e 3a 20 44 54 4e 31 34 30 35 38 30 43 48 0d 0a 0d 0a 0d

As you theoutput of show inventory command is OK, but there is no result on the GUI interface TAB Modules

Thank your for your help

Best regards,

**Comment by SCadilhac** [comment]
Could you try with driver version 1.5 (998de31f1b8865bf53661883bf8f6811fc05bef7)?
