### ISSUE TITLE
Question - Hourly snapshots?

### ISSUE THREAD

**Issue by Kriztofen** [netfishers-onl/Netshot#93]
Hi again,

I'm attempting to set scheduled snapshots to run once an hour but it looks like the minimum is daily:

![image](https://user-images.githubusercontent.com/32734784/105045254-a0bbfe80-5a5f-11eb-9a71-0996e6d674a5.png)

Is it simply me missing something again or is Netshot not built to support that frequent amount of snapshotting? 

For testing I don't mind setting 24 repeating snapshots but it may become a bit cumbersome if we decide to add all of our kit to it.

Thanks in advance :)

Best Regards,

Chris

**Comment by SCadilhac** [comment]
Indeed, that's not supported currently, first time I see this is a limitation. Most of the time, forced snapshots are not scheduled that often, as Netshot can rely on SNMP traps and/or Syslog messages to trigger on-demand snapshots (whenever a change actually occurs to a device).

**Comment by SCadilhac** [comment]
b23970897302fc731e2e87d4cd2232c84daf8fee adds this feature.

**Comment by SCadilhac** [comment]
![image](https://user-images.githubusercontent.com/14115661/106402210-bf8b9f00-6428-11eb-8dba-1ebc5dad7ea1.png)
