### ISSUE TITLE
Device-based exemptions doesn't work in Compliance rule

### ISSUE THREAD

**Issue by Najihel** [netfishers-onl/Netshot#94]
Hi,

It's not possible to selecte devices in device-base exemptions.

![netshoot-exemption-compliance](https://user-images.githubusercontent.com/1873677/105194273-b1d93e00-5b39-11eb-882c-e840b6d91c3e.gif)

NetShot version : 0.15.2

**Comment by SCadilhac** [comment]
Fixed 457b904f94ac0eb0d6a6faa19c380202c2edfc20
Thanks for reporting.
