### ISSUE TITLE
Error when adding a domain: Invalid IP address 

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#99]
Hello.

I am trying to do the initial setup of NetShot and I am stuck to the step where a domain has to be added (it looks like this part is missing from the documentation)

I have no idea what IP I am supposed to put here ? I tried differents IP but I always get the following error from the GUI : " Error: Invalid IP address" and from the API: "RestService: User posted an invalid IP address."

When checking the code it matches this condition where it should not : https://github.com/netfishers-onl/Netshot/blob/7693383e9822dce47bd45e0da4c1e43d6a766cb0/src/main/java/onl/netfishers/netshot/rest/RestService.java#L574

The addresses I am giving are unicast (but I don't even know how does it get the subnet masks if it's only asking for the IP address, how to it knows if it's unicast or not ?)

**Comment by SCadilhac** [comment]
Fixed in 86462df6d5f2a1667ad8fc8c1caf27d8bf12d161
Was due to some cleanup I made in last version.

**Comment by kedare** [comment]
Thanks, indeed it's working now but it's not very clear which IP am I supposed to put there ? (I have put the IP of the netshot instance used to connect to the devices assuming it's that)

**Comment by SCadilhac** [comment]
You can refer to this for some explanation: https://github.com/netfishers-onl/Netshot/wiki/Netshot-User-Guide#device-domains
It is indeed supposed to be IP the address of the Netshot server as seen per the devices, in case a driver would need to have the device upload data to the server... which doesn't happen at the moment.

**Comment by tbiens** [comment]
Hello,

I have a fresh install using the latest release and fell into this bug. What should I do to move past this?

**Comment by SCadilhac** [comment]
I will release a new package with the fix very soon.

**Comment by tbiens** [comment]
Thank you!

**Comment by SCadilhac** [comment]
Version 0.16.1 is published.

**Comment by tbiens** [comment]
Problem solved in new release. Thanks!
